"""
xtal.io.cif_writer
==================
Writing CIF files.

The export is deliberately minimal: cell, symmetry, atoms, and a note
saying which program produced the file.  No refinement history, no
diffractometer block, no invented uncertainties -- writing tags we did
not compute would be dressing a built model up as a measurement.

Written by hand rather than through gemmi so the output stays exactly
what we intend it to be, line for line.
"""

from __future__ import annotations

import datetime
from pathlib import Path

from xtal.core.structure import Structure

PROGRAM = "Crystal Builder"


def _version() -> str:
    from xtal import __version__
    return __version__


def _block_name(structure: Structure, fallback: str) -> str:
    raw = str(structure.meta.get("title") or fallback or "structure")
    cleaned = "".join(c if (c.isalnum() or c in "_-+.") else "_"
                      for c in raw.strip())
    return cleaned or "structure"


def _quote(value: str) -> str:
    text = str(value)
    if not text:
        return "?"
    if any(c in text for c in " \t'\"") or text[0] in "_#$[];":
        return "'" + text.replace("'", " ") + "'"
    return text


def write_cif(structure: Structure, path, expand_to_p1: bool = False,
              title: str | None = None) -> Path:
    """Write ``structure`` to ``path``.

    ``expand_to_p1`` writes every atom of the cell in P1 instead of the
    asymmetric unit plus its symmetry -- useful for programs that do
    not apply symmetry operations themselves.
    """
    path = Path(path)
    path.write_text(cif_string(structure, expand_to_p1=expand_to_p1,
                               title=title or path.stem))
    return path


def cif_string(structure: Structure, expand_to_p1: bool = False,
               title: str | None = None) -> str:
    """The CIF text for a structure (what the clipboard gets too)."""
    from xtal.core.symmetry import reduce_to_p1

    source = reduce_to_p1(structure) if expand_to_p1 else structure
    a, b, c, alpha, beta, gamma = source.lattice.parameters
    group = source.space_group
    today = datetime.date.today().isoformat()
    version = _version()

    lines = [
        f"# Generated by {PROGRAM} {version}",
        "# Structural data only: cell, symmetry and atomic sites.",
        "",
        f"data_{_block_name(source, title)}",
        "",
        f"_audit_creation_method    {_quote(f'{PROGRAM} {version}')}",
        f"_audit_creation_date      {today}",
    ]
    formula = _formula_sum(source)
    if formula:
        lines.append(f"_chemical_formula_sum     {_quote(formula)}")

    lines += [
        "",
        f"_cell_length_a            {a:.6f}",
        f"_cell_length_b            {b:.6f}",
        f"_cell_length_c            {c:.6f}",
        f"_cell_angle_alpha         {alpha:.4f}",
        f"_cell_angle_beta          {beta:.4f}",
        f"_cell_angle_gamma         {gamma:.4f}",
        f"_cell_volume              {source.lattice.volume:.4f}",
        "",
        f"_space_group_name_H-M_alt {_quote(group.hm)}",
        f"_space_group_name_Hall    {_quote(group.hall)}",
        f"_space_group_IT_number    {group.number}",
        "",
        "loop_",
        "_space_group_symop_id",
        "_space_group_symop_operation_xyz",
    ]
    for n, triplet in enumerate(group.triplets, start=1):
        lines.append(f"{n:4d}  {_quote(triplet)}")

    lines += ["", "loop_", "_atom_site_label", "_atom_site_type_symbol",
              "_atom_site_fract_x", "_atom_site_fract_y",
              "_atom_site_fract_z", "_atom_site_occupancy"]
    has_uiso = any(s.u_iso is not None for s in source.sites)
    if has_uiso:
        lines.append("_atom_site_U_iso_or_equiv")

    labelled = source.copy()
    labelled.ensure_labels()
    for site in labelled.sites:
        x, y, z = site.frac
        row = (f"{site.label:<8s} {_type_symbol(site):<5s} "
               f"{x: .6f} {y: .6f} {z: .6f} {site.occupancy:8.4f}")
        if has_uiso:
            u = site.u_iso if site.u_iso is not None else 0.0
            row += f" {u:8.5f}"
        lines.append(row)

    lines += _aniso_loop(labelled)
    lines.append("")
    return "\n".join(lines)


def _aniso_loop(structure) -> list[str]:
    """The ``_atom_site_aniso_*`` loop, when anything has one.

    Only the sites that were actually refined anisotropically get a
    row.  A CIF's aniso loop is *sparse* by design -- the hydrogens
    usually have none -- and padding it with zeros would claim six
    measurements that were never made.
    """
    rows = [s for s in structure.sites if s.u_aniso is not None]
    if not rows:
        return []
    lines = ["", "loop_", "_atom_site_aniso_label",
             "_atom_site_aniso_U_11", "_atom_site_aniso_U_22",
             "_atom_site_aniso_U_33", "_atom_site_aniso_U_12",
             "_atom_site_aniso_U_13", "_atom_site_aniso_U_23"]
    for site in rows:
        u11, u22, u33, u12, u13, u23 = site.u_aniso
        lines.append(f"{site.label:<8s} {u11: .5f} {u22: .5f} "
                     f"{u33: .5f} {u12: .5f} {u13: .5f} {u23: .5f}")
    return lines


def _type_symbol(site) -> str:
    """Element with its oxidation state, CIF style: Ti4+, O2-.

    Only whole-number charges are written: a fractional charge is a
    computed quantity (a QEq or Mulliken charge), not part of the
    structure, and CIF has no honest place for it here.
    """
    charge = site.charge
    if charge is None or abs(charge - round(charge)) > 1e-6:
        return site.element
    n = int(round(charge))
    if n == 0:
        return site.element
    return f"{site.element}{abs(n)}{'+' if n > 0 else '-'}"


def _formula_sum(structure: Structure) -> str:
    from xtal.core.properties import cell_contents
    counts = cell_contents(structure)
    if not counts:
        return ""
    return " ".join(
        f"{sym}{count:g}" for sym, count in sorted(counts.items()))
