"""
xtal.io.cif_writer
==================
Writing CIF files.

The export is deliberately minimal: cell, symmetry, atoms, the bonds,
and a note saying which program produced the file.  No refinement
history, no diffractometer block, no invented uncertainties -- writing
tags we did not compute would be dressing a built model up as a
measurement.

**The bonds go in the file.**  This used to be the one thing a CIF was
said to have nowhere for, and it was not true: ``_geom_bond`` has been
in the dictionary all along and its ``site_symmetry_2`` code is
exactly (operation, lattice translation), which is what a bond here
is.  So a framework keeps the net drawn over it, a marker keeps the
edge it was added for, and the file is still a CIF anything else can
read.  What is left over -- what a bond *means* to this application --
goes in ``_xtal_bond_*`` tags in the same loop, which every other
reader skips.  :func:`xtal.io.export.for_export` is what strips both
back out for a file leaving this application.

Written by hand rather than through gemmi so the output stays exactly
what we intend it to be, line for line.
"""

from __future__ import annotations

import datetime
from pathlib import Path

import numpy as np

from xtal.core.structure import Structure

PROGRAM = "Crystal Builder"


def _version() -> str:
    from xtal import __version__
    return __version__


def _block_name(structure: Structure, fallback: str) -> str:
    raw = str(structure.meta.get("title") or fallback or "structure")
    cleaned = "".join(c if (c.isalnum() or c in "_-+.") else "_"
                      for c in raw.strip())
    return cleaned or "structure"


#: Words a bare CIF value may not begin with: they open a block, a loop
#: or a save frame, so a value spelled like one has to be quoted.
_RESERVED = ("data_", "loop_", "global_", "save_", "stop_")


def _quote(value: str) -> str:
    """A CIF value, quoted only when it has to be, and never damaged.

    CIF 1.1 has no escape character, so a quoted string is delimited by
    whichever quote it does not itself contain.  This used to substitute
    a space for every apostrophe, which turned ``Na'1`` into ``Na 1``:
    two tokens where the file said one, silently, with no way back.
    A label containing both quote characters cannot be delimited at all
    and becomes a semicolon text field -- legal anywhere a value is,
    including inside a loop, because a newline is only whitespace.
    """
    text = str(value)
    if not text:
        return "?"
    lowered = text.lower()
    plain = (not any(c in text for c in " \t\n'\"")
             and text[0] not in "_#$[];"
             and not lowered.startswith(_RESERVED))
    if plain:
        return text
    if "'" not in text and "\n" not in text:
        return f"'{text}'"
    if '"' not in text and "\n" not in text:
        return f'"{text}"'
    return f"\n;{text}\n;"


def write_cif(structure: Structure, path, expand_to_p1: bool = False,
              title: str | None = None,
              perception: bool = False) -> Path:
    """Write ``structure`` to ``path``.

    ``expand_to_p1`` writes every atom of the cell in P1 instead of the
    asymmetric unit plus its symmetry -- useful for programs that do
    not apply symmetry operations themselves.  ``perception`` writes
    the stored distance-perceived graph as well; see
    :func:`_perception_loop`.
    """
    path = Path(path)
    path.write_text(cif_string(structure, expand_to_p1=expand_to_p1,
                               title=title or path.stem,
                               perception=perception),
                    encoding="utf-8")
    return path


def cif_string(structure: Structure, expand_to_p1: bool = False,
               title: str | None = None,
               perception: bool = False) -> str:
    """The CIF text for a structure (what the clipboard gets too)."""
    from xtal.core.symmetry import reduce_to_p1

    source = reduce_to_p1(structure) if expand_to_p1 else structure
    a, b, c, alpha, beta, gamma = source.lattice.parameters
    group = source.space_group
    today = datetime.date.today().isoformat()
    version = _version()

    lines = [
        f"# Generated by {PROGRAM} {version}",
        "# Structural data only: cell, symmetry and atomic sites.",
        "",
        f"data_{_block_name(source, title)}",
        "",
        f"_audit_creation_method    {_quote(f'{PROGRAM} {version}')}",
        f"_audit_creation_date      {today}",
    ]
    formula = _formula_sum(source)
    if formula:
        lines.append(f"_chemical_formula_sum     {_quote(formula)}")

    lines += [
        "",
        f"_cell_length_a            {a:.6f}",
        f"_cell_length_b            {b:.6f}",
        f"_cell_length_c            {c:.6f}",
        f"_cell_angle_alpha         {alpha:.4f}",
        f"_cell_angle_beta          {beta:.4f}",
        f"_cell_angle_gamma         {gamma:.4f}",
        f"_cell_volume              {source.lattice.volume:.4f}",
        "",
        f"_space_group_name_H-M_alt {_quote(group.hm)}",
        f"_space_group_name_Hall    {_quote(group.hall)}",
        f"_space_group_IT_number    {group.number}",
        "",
        "loop_",
        "_space_group_symop_id",
        "_space_group_symop_operation_xyz",
    ]
    for n, triplet in enumerate(group.triplets, start=1):
        lines.append(f"{n:4d}  {_quote(triplet)}")

    lines += ["", "loop_", "_atom_site_label", "_atom_site_type_symbol",
              "_atom_site_fract_x", "_atom_site_fract_y",
              "_atom_site_fract_z", "_atom_site_occupancy"]
    has_uiso = any(s.u_iso is not None for s in source.sites)
    if has_uiso:
        lines.append("_atom_site_U_iso_or_equiv")

    labelled = source.copy()
    labelled.ensure_labels()
    for site in labelled.sites:
        x, y, z = site.frac
        row = (f"{_quote(site.label):<8s} {_quote(_type_symbol(site)):<5s} "
               f"{x: .6f} {y: .6f} {z: .6f} {site.occupancy:8.4f}")
        if has_uiso:
            u = site.u_iso if site.u_iso is not None else 0.0
            row += f" {u:8.5f}"
        lines.append(row)

    lines += _aniso_loop(labelled)
    lines += _bond_loop(labelled)
    if perception and not expand_to_p1:
        lines += _perception_loop(source)
    lines.append("")
    return "\n".join(lines)


def _bond_loop(structure) -> list[str]:
    """The ``_geom_bond_*`` loop, and what only this program reads.

    ``_geom_bond_site_symmetry_2`` is the ``n_pqr`` code: operation
    *n* of the symmetry loop written above, then a lattice translation
    of ``(p - 5, q - 5, r - 5)``.  That is
    :class:`~xtal.core.structure.Bond`'s ``op`` and ``image`` with
    nothing left over, so the standard half of this loop is the whole
    geometry and another program reads the bonds this one drew.

    Three things standard CIF has no vocabulary for follow it: the
    order, whether the order was *stated* by the user or inferred, and
    the ``kind`` -- a net edge is not a chemical bond and a
    suppression is the record of one deliberately deleted.  The image
    is repeated among them because ``n_pqr`` cannot spell a
    translation beyond four cells, and a net edge is under no
    obligation to stay inside one.

    The private tags are also the *signal*: a foreign CIF's
    ``_geom_bond`` loop is usually a distance table from a refinement
    rather than a bond graph, so the reader takes this loop only when
    ``_xtal_bond_kind`` is in it.  See
    :func:`xtal.io.cif_reader.read_bonds`.
    """
    bonds = [b for b in structure.bonds
             if 0 <= b.i < len(structure.sites)
             and 0 <= b.j < len(structure.sites)]
    if not bonds:
        return []
    lines = ["", "loop_", "_geom_bond_atom_site_label_1",
             "_geom_bond_atom_site_label_2",
             "_geom_bond_site_symmetry_2", "_geom_bond_distance",
             "_xtal_bond_image", "_xtal_bond_order",
             "_xtal_bond_kind", "_xtal_bond_stated"]
    for bond in bonds:
        one = _quote(structure.sites[bond.i].label)
        two = _quote(structure.sites[bond.j].label)
        distance = _bond_distance(structure, bond)
        image = ",".join(str(int(t)) for t in bond.image)
        lines.append(
            f"{one:<8s} {two:<8s} {_symmetry_code(bond):<8s} "
            f"{'?' if distance is None else format(distance, '.4f'):>8s}"
            f"  {image:<10s} {bond.order:6.3f} "
            f"{bond.kind:<12s} {'yes' if bond.stated else 'no'}")
    return lines


#: The loop holding a stored perception, one P1 bond a row.
PERCEIVED_TAGS = ("_xtal_perceived_bond_atom_1",
                  "_xtal_perceived_bond_atom_2",
                  "_xtal_perceived_bond_image",
                  "_xtal_perceived_bond_distance")
#: How many atoms the cell those rows index had.
PERCEIVED_COUNT = "_xtal_perceived_cell_atoms"


def _perception_loop(structure) -> list[str]:
    """The distance-perceived graph, as it is stored, P1 bond by bond.

    For a file whose geometry is not the one its bonds were perceived
    at -- a point of a relaxed scan, whose cell is 15% wider than the
    crystal the scan held the bonding of.  Without this the file holds
    only the bonds the user drew, and opening it perceives afresh at
    the stretched geometry: MIL-53 loses 24 of its 126 bonds at +15%
    on *a*, and the structure behind a cell of the landscape is not
    the molecule the landscape was scored over.

    Written against the coordinates *as printed*, six decimals, since
    that is the cell the reader will expand: an atom a rounding place
    inside a face is outside it once read back, and every image it is
    in moves by one.  Nothing when there is no stored graph -- this
    records an answer, it does not compute one.
    """
    from xtal.core import bonding, p1

    if structure.perceived is None:
        return []
    cell = p1.expand(structure)
    bonds = bonding.perceive(structure, include_explicit=False)
    printed = structure.copy()
    for site in printed.sites:
        site.frac = [float(f"{v:.6f}") for v in site.frac]
    read_back = p1.expand(printed)
    if read_back.elements != cell.elements:
        return []                               # pragma: no cover
    bonds = bonding.rebase(bonds, cell.tau, read_back.tau)
    lines = ["", f"{PERCEIVED_COUNT} {read_back.n_atoms}",
             "", "loop_", *PERCEIVED_TAGS]
    # The length now, not the one stored: the graph was perceived at
    # some other geometry, and the reader checks each bond against
    # the cell it has in front of it.
    matrix = printed.lattice.matrix
    for bond in bonds:
        image = ",".join(str(int(t)) for t in bond.image)
        length = np.linalg.norm(
            (read_back.frac[bond.j] + np.asarray(bond.image)
             - read_back.frac[bond.i]) @ matrix)
        lines.append(f"{bond.i:6d} {bond.j:6d} {image:<10s} "
                     f"{length:.4f}")
    return lines


def _symmetry_code(bond) -> str:
    """``n_pqr`` for a bond, or ``.`` when it will not fit.

    One digit per axis is the format, so a translation of five cells
    or more has no spelling here -- ``_xtal_bond_image`` is written
    for every bond precisely so that the answer never depends on this
    one fitting.
    """
    if max(abs(int(t)) for t in bond.image) > 4:
        return "."
    p, q, r = (5 + int(t) for t in bond.image)
    return f"{bond.op + 1}_{p}{q}{r}"


def _bond_distance(structure, bond) -> float | None:
    """How long the bond is, in angstroms.

    Computed rather than remembered, and ``None`` when the operation
    it names is not in the group any more -- which is a bond about to
    be dropped, not a distance worth guessing at.
    """
    ops = structure.space_group.operations
    if not 0 <= bond.op < len(ops):
        return None
    target = (ops[bond.op].apply(structure.sites[bond.j].frac)
              + np.asarray(bond.image, dtype=float))
    delta = target - np.asarray(structure.sites[bond.i].frac,
                                dtype=float)
    return float(np.linalg.norm(structure.lattice.to_cart(delta)))


def _aniso_loop(structure) -> list[str]:
    """The ``_atom_site_aniso_*`` loop, when anything has one.

    Only the sites that were actually refined anisotropically get a
    row.  A CIF's aniso loop is *sparse* by design -- the hydrogens
    usually have none -- and padding it with zeros would claim six
    measurements that were never made.
    """
    rows = [s for s in structure.sites if s.u_aniso is not None]
    if not rows:
        return []
    lines = ["", "loop_", "_atom_site_aniso_label",
             "_atom_site_aniso_U_11", "_atom_site_aniso_U_22",
             "_atom_site_aniso_U_33", "_atom_site_aniso_U_12",
             "_atom_site_aniso_U_13", "_atom_site_aniso_U_23"]
    for site in rows:
        u11, u22, u33, u12, u13, u23 = site.u_aniso
        lines.append(f"{_quote(site.label):<8s} {u11: .5f} {u22: .5f} "
                     f"{u33: .5f} {u12: .5f} {u13: .5f} {u23: .5f}")
    return lines


def _type_symbol(site) -> str:
    """Element with its oxidation state, CIF style: Ti4+, O2-.

    Only whole-number charges are written: a fractional charge is a
    computed quantity (a QEq or Mulliken charge), not part of the
    structure, and CIF has no honest place for it here.
    """
    charge = site.charge
    if charge is None or abs(charge - round(charge)) > 1e-6:
        return site.element
    n = int(round(charge))
    if n == 0:
        return site.element
    return f"{site.element}{abs(n)}{'+' if n > 0 else '-'}"


def _formula_sum(structure: Structure) -> str:
    from xtal.core.properties import cell_contents
    counts = cell_contents(structure)
    if not counts:
        return ""
    return " ".join(
        f"{sym}{count:g}" for sym, count in sorted(counts.items()))
