"""Sphinx configuration for the Crystal Builder manual.

    sphinx-build -b html docs/manual build/manual/html
    sphinx-build -M latexpdf docs/manual build/manual

MyST Markdown pages, a BibTeX bibliography cited by number, and a PDF
laid out as a book: numbered chapters, a running header naming the
release, and lettered appendices for the generated reference, the
change log, the glossary and the bibliography.  The release is the
installed package's, so a manual built from a tag says which version it
describes.

The pages under ``reference/`` are generated by
``.claude/skills/manual-writing/reference.py`` and are never edited by
hand.
"""

from __future__ import annotations

import subprocess
from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as installed_version
from pathlib import Path

project = "Crystal Builder"
author = "The Crystal Builder developers"
copyright = "Crystal Builder developers, MIT licence"


def _release() -> str:
    """The version this checkout is, from git as setuptools_scm reads it.

    Not the installed package's: an editable install keeps the version
    it was installed at, and a manual built today said 0.2.1 of a tree
    two releases on.  A tag builds as its number; anything after it as
    the tag and how far past it, which is what the manual describes.
    """
    try:
        described = subprocess.run(
            ["git", "describe", "--tags", "--always"],
            cwd=Path(__file__).parent, capture_output=True, text=True,
            check=True).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        try:
            return installed_version("crystal-builder")
        except PackageNotFoundError:
            return "development"
    tag, _, rest = described.lstrip("v").partition("-")
    if not rest:
        return tag
    commits = rest.split("-")[0]
    return f"{tag} (development, {commits} commits on)"


release = _release()
version = release.split(" ")[0]

extensions = [
    "myst_parser",
    "sphinxcontrib.bibtex",
    "sphinx.ext.mathjax",
]
source_suffix = {".md": "markdown"}
root_doc = "index"
exclude_patterns = ["_build", "reference/inventory.json"]

myst_enable_extensions = [
    "colon_fence",      # ::: admonitions
    "deflist",
    "dollarmath",       # $...$ and $$...$$
    "amsmath",
    "fieldlist",
    "substitution",
]
myst_heading_anchors = 3
myst_substitutions = {"release": release}

# Cited by number, in order of first citation, as a methods manual is.
bibtex_bibfiles = ["references.bib"]
bibtex_default_style = "unsrt"
bibtex_reference_style = "label"

numfig = True
numfig_secnum_depth = 1

html_theme = "furo"
html_title = f"Crystal Builder {release}"

latex_engine = "xelatex"          # accented author names and en dashes
latex_documents = [
    ("index", "crystal-builder-manual.tex", "Crystal Builder Manual",
     author, "manual"),
]
# The appendices are marked in index.md with a raw \appendix, so every
# page stays in the one toctree the HTML build also reads.
latex_elements = {
    "papersize": "a4paper",
    "pointsize": "10pt",
    "fncychap": r"\usepackage[Bjarne]{fncychap}",
    # The menu-path separator the application draws, which the default
    # font has no glyph for: a small solid triangle, as in the menus.
    "preamble": r"""\setcounter{tocdepth}{1}
\usepackage{amssymb}
\usepackage{newunicodechar}
\newunicodechar{▸}{\ensuremath{\blacktriangleright}}
""",
    "printindex": r"\footnotesize\raggedright\printindex",
    # No icons in the admonition titles: TeX Live before 2020 has no
    # FontAwesome font XeLaTeX can find, and the words say it anyway.
    # verbatimforcewraps lets a literal line with no space in it -- the
    # {info,symmetry,...,run} token of `xtal --help` -- break instead
    # of running off the page.
    "sphinxsetup": "iconpackage=none,verbatimforcewraps=true",
}
latex_show_urls = "footnote"
# makeindex, not xindy: the xindy in TeX Live 2016 is a binary macOS no
# longer runs, and an English index needs nothing xindy adds.
latex_use_xindy = False
