"""The manual's reference pages, generated from the application.

    reference.py [-o docs/manual/reference]

Writes MyST Markdown that Sphinx reads:

``commands.md``
    Every registry command, grouped the way the menu bar groups it,
    with its label, shortcut, tip and registry key.
``modules.md``
    Every module, its entries, and every setting each asks for: kind,
    range, default, help.
``engines.md``
    Every force-field engine and its options.
``panels.md``
    Every dock: title, where it opens, the class's own first sentence.
``inventory.json``
    The same, as data, for checking coverage of the hand-written
    chapters.

Each command, module entry, engine and panel gets a stable label --
``(cmd-recompute_bonds)=``, ``(mod-zeopp-diameters)=`` -- so prose
chapters cross-reference them and an in-application help button can
open the right place.  Labels are built from registry keys, never from
the wording, so a rewording does not break a link.

The same live objects the Help window reads (``xtalapp.dialogs.help``)
are the source, so this and the Help window cannot disagree, and a
reference chapter is regenerated rather than rewritten after a change.
It builds a real ``MainWindow`` with a stub viewport, in scratch
preferences and a scratch workspace, and never shows it.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

_SCRATCH = tempfile.mkdtemp(prefix="xtal-manual-")
os.environ.setdefault("QT_API", "pyside6")
os.environ["XTAL_NO_CONFIRM_CLOSE"] = "1"
os.environ["XTAL_SETTINGS_DIR"] = str(Path(_SCRATCH) / "settings")
os.environ["XTAL_WORKSPACE_ROOT"] = str(Path(_SCRATCH) / "workspace")

HEADER = ("<!-- Generated by .claude/skills/manual-writing/reference.py."
          "  Do not edit: change the tip, the Param help or the "
          "docstring in the source, and regenerate. -->\n\n")


def _cell(text) -> str:
    """Safe inside a Markdown table cell."""
    return str(text).replace("|", "\\|").replace("\n", " ").strip()


def _window():
    from PySide6.QtWidgets import QApplication, QWidget

    from xtal import plugins
    from xtalapp.mainwindow import MainWindow

    class _Stub(QWidget):
        def __init__(self, document=None, parent=None):
            super().__init__(parent)
            self.document = document

    from xtalapp.application import keep_siblings_non_native

    plugins.load()
    keep_siblings_non_native()
    app = QApplication.instance() or QApplication([sys.argv[0]])
    return app, MainWindow(viewport_factory=_Stub)


def _commands(window) -> list[dict]:
    """``command_sections``, with the registry key each row came from."""
    from xtalapp.dialogs import help as h

    known = h._registry_names(window)
    seen: set[str] = set()
    out = []

    def walk(menu, section, prefix):
        for action in menu.actions():
            if action.isSeparator():
                continue
            if action.menu() is not None:
                walk(action.menu(), section,
                     f"{prefix}{h._clean(action.text())} ▸ ")
                continue
            key = known.get(id(action))
            if key is None or key in seen:
                continue
            seen.add(key)
            out.append({"key": key, "section": section,
                        "path": prefix + h._clean(action.text()),
                        "shortcut": h._shortcut(action),
                        "tip": h._tip(action),
                        "checkable": action.isCheckable()})

    for top in window.menuBar().actions():
        if top.menu() is not None:
            walk(top.menu(), h._clean(top.text()), "")
    for key in window.actions_.names():
        if key not in seen:
            action = window.actions_[key]
            out.append({"key": key, "section": "Elsewhere",
                        "path": h._clean(action.text()),
                        "shortcut": h._shortcut(action),
                        "tip": h._tip(action),
                        "checkable": action.isCheckable()})
    return out


def _params(params) -> list[dict]:
    from xtalapp.dialogs.help import param_range
    return [{"name": p.name, "label": p.title, "accepts": param_range(p),
             "default": str(p.default_value()), "help": p.help}
            for p in params]


def _modules() -> list[dict]:
    from xtal.modules import MODULES
    from xtalapp.dialogs.help import _clean
    return [{"name": m.name, "label": m.label,
             "description": m.description,
             "actions": [{"name": a.name, "label": _clean(a.label),
                          "tip": a.tip, "dialog": a.dialog,
                          "shell": a.shell,
                          "params": _params(a.params)}
                         for a in m.actions]}
            for m in MODULES]


def _engines() -> list[dict]:
    from xtal.ff import ENGINES
    return [{"name": e.name, "label": e.label,
             "description": e.description,
             "provides": sorted(e.provides),
             "options": _params(e.options)}
            for e in ENGINES]


def _panels(window) -> list[dict]:
    import inspect
    names = {id(v): k for k, v in vars(window).items()}
    areas = [("left", window.left_docks), ("right", window.right_docks),
             ("bottom", window.bottom_docks)]
    out = []
    for area, docks in areas:
        for dock in docks:
            doc = inspect.getdoc(type(dock)) or ""
            out.append({"key": names.get(id(dock), ""),
                        "title": dock.windowTitle(), "area": area,
                        "class": type(dock).__name__,
                        "summary": " ".join(doc.split("\n\n")[0].split())})
    return out


def _default(value) -> str:
    """A default as code, or nothing: an empty one printed as a pair of
    backticks."""
    text = _cell(value)
    if not text:
        return ""
    # Code cannot break, so a long name -- orb-v3-conservative-inf-omat
    # -- ran 105 pt past the margin of the PDF; as text it breaks at
    # its hyphens.
    return f"`{text}`" if len(text) <= 14 else text


def _params_table(params) -> list[str]:
    if not params:
        return ["No settings.", ""]
    # Column widths for the PDF, as fractions of the line: without them
    # LaTeX shares the width out by content and a long description
    # squeezes the header to "Set- ting".  HTML ignores the directive.
    rows = ["```{tabularcolumns} |\\Y{0.18}|\\Y{0.2}|\\Y{0.18}|\\Y{0.44}|",
            "```", "",
            "| Setting | Accepts | Default | What it is |",
            "|---|---|---|---|"]
    rows += [f"| **{_cell(p['label'])}** | {_cell(p['accepts'])} | "
             f"{_default(p['default'])} | {_cell(p['help'])} |"
             for p in params]
    return rows + [""]


def write(out: Path, commands, modules, engines, panels) -> None:
    out.mkdir(parents=True, exist_ok=True)

    lines = [HEADER + "# Command reference", ""]
    section = None
    for c in commands:
        if c["section"] != section:
            section = c["section"]
            lines += [f"## {section}", ""]
        key = f" · {c['shortcut']}" if c["shortcut"] else ""
        lines += [f"(cmd-{c['key']})=",
                  f"### {c['path']}",
                  "",
                  f"`{c['key']}`{key}"
                  + (" · toggle" if c["checkable"] else ""),
                  "",
                  c["tip"] or "*No description yet.*",
                  "",
                  f"```{{index}} {c['path'].split(' ▸ ')[-1]}",
                  "```", ""]
    (out / "commands.md").write_text("\n".join(lines))

    lines = [HEADER + "# Module reference", ""]
    for m in modules:
        lines += [f"(mod-{m['name']})=", f"## {m['label']}", "",
                  m["description"], "",
                  f"```{{index}} {m['label']}", "```", ""]
        for a in m["actions"]:
            lines += [f"(mod-{m['name']}-{a['name']})=",
                      f"### {a['label']}", "", a["tip"], ""]
            lines += _params_table(a["params"])
    (out / "modules.md").write_text("\n".join(lines))

    lines = [HEADER + "# Force-field engines", ""]
    for e in engines:
        lines += [f"(engine-{e['name']})=", f"## {e['label']}", "",
                  e["description"], "",
                  "Provides: " + (", ".join(e["provides"]) or "energy"),
                  ""]
        lines += _params_table(e["options"])
    (out / "engines.md").write_text("\n".join(lines))

    lines = [HEADER + "# Panels", "",
             "```{tabularcolumns} |\\Y{0.2}|\\Y{0.15}|\\Y{0.65}|", "```",
             "", "| Panel | Opens on the | What it is |", "|---|---|---|"]
    lines += [f"| {{ref}}`{_cell(p['title'])} <panel-{p['key']}>` | "
              f"{p['area']} | {_cell(p['summary'])} |" for p in panels]
    lines.append("")
    for p in panels:
        lines += [f"(panel-{p['key']})=", f"## {p['title']}", "",
                  p["summary"], ""]
    (out / "panels.md").write_text("\n".join(lines))

    (out / "inventory.json").write_text(json.dumps(
        {"commands": commands, "modules": modules, "engines": engines,
         "panels": panels}, indent=1, ensure_ascii=False))


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    p.add_argument("-o", "--output", default="docs/manual/reference")
    args = p.parse_args(argv)
    out = (ROOT / args.output).resolve()

    app, window = _window()
    commands = _commands(window)
    panels = _panels(window)
    window.close()
    modules, engines = _modules(), _engines()
    write(out, commands, modules, engines, panels)

    missing = [c["key"] for c in commands if not c["tip"]]
    params = [f"{m['name']}.{a['name']}.{q['name']}"
              for m in modules for a in m["actions"]
              for q in a["params"] if not q["help"]]
    # An engine's options are the Force Field panel's form and print
    # in the same tables, so they are short of help in the same way.
    params += [f"engine.{e['name']}.{q['name']}" for e in engines
               for q in e["options"] if not q["help"]]
    print(f"wrote {len(commands)} commands, "
          f"{sum(len(m['actions']) for m in modules)} module entries, "
          f"{len(engines)} engines, {len(panels)} panels to {out}")
    print(f"{len(missing)} commands have no tip: {', '.join(missing)}")
    print(f"{len(params)} settings have no help: {', '.join(params)}")
    del app
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
