"""
xtal.core.p1
============
Expanding an asymmetric unit into the full contents of the unit cell.

A :class:`P1Cell` is *derived* data -- it is never edited directly and
never stored in a document.  What makes it more than a list of
coordinates is the provenance it carries for every atom:

    frac[k] = ops[op_idx[k]].apply(sites[site_idx[k]].frac) + tau[k]

That triple (parent site, operation, lattice shift) is what lets the
application do the two things a symmetry-aware editor must do:

* draw a symmetry image and know which asymmetric site it belongs to
  when the user clicks it;
* take a *new* position for an image atom and map it back through the
  inverse operation onto the parent site, so the whole orbit moves
  together (:func:`parent_coordinates`).

Atoms that coincide -- an atom on a special position, where several
operations produce the same point -- are generated once.  The number of
survivors from one site is its multiplicity.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np

from xtal.core.lattice import Lattice

# Two generated positions closer than this (in Angstrom) are the same
# atom on a special position.  It is not a numerical tolerance and must
# not be sized like one: a site is on a special position when the
# coordinates *say* it is, and coordinates say so to four decimal
# places on a thirty-Angstrom cell -- 0.003 A -- or to whatever an
# optimiser step or a drag last left them at.  This was 1e-3, which is
# below the precision of a published CIF, and a Zn 0.06 A off a mirror
# in MFU-4l was therefore generated by every operation that should have
# mapped it onto itself: multiplicity 96 where the file says 32, 712
# atoms in a cell that holds 648, and the formula, the density and
# every energy computed from them wrong with nothing on screen saying
# so.  Nothing reported it because duplicate merging compares a site
# against *other* sites' images and never against its own, so the only
# thing that ever showed it was Reduce to P1 -- which was blamed for
# making the duplicates it was the first to draw.
#
# No two distinct atoms are this close, so the test cannot merge an
# atom that is really there; and the count is flat from 0.01 A to
# 0.2 A on every structure in resources/samples, so it is not perched
# on the edge of an answer.  Coordinates are left where the user put
# them -- the first operation to reach a point still wins, and for a
# site near a special position that is the identity.  Snapping a site
# *onto* its special position is idealisation, and Standardize is
# where that lives.
SPECIAL_POSITION_TOL = 0.05


@dataclass(frozen=True)
class P1Cell:
    """Every atom of the unit cell, with its symmetry provenance."""

    lattice: Lattice
    frac: np.ndarray                # (N,3) in [0,1)
    site_idx: np.ndarray            # (N,) parent site index
    op_idx: np.ndarray              # (N,) operation index
    tau: np.ndarray                 # (N,3) int lattice shift
    elements: tuple[str, ...]
    occupancy: np.ndarray           # (N,)
    labels: tuple[str, ...]
    # Lazily-built lookups; a P1Cell is immutable, so these are pure
    # memoisation and never part of its identity.
    _index: dict = field(default_factory=dict, repr=False,
                         compare=False)

    @property
    def n_atoms(self) -> int:
        return len(self.frac)

    def __len__(self) -> int:
        return len(self.frac)

    @property
    def cart(self) -> np.ndarray:
        return self.lattice.to_cart(self.frac)

    @property
    def numbers(self) -> np.ndarray:
        from xtal.core import elements as el
        return np.array([el.atomic_number(s) for s in self.elements])

    def multiplicity(self, site_index: int) -> int:
        """How many atoms this asymmetric site generates."""
        counts = self._counts
        if 0 <= site_index < len(counts):
            return int(counts[site_index])
        return 0

    def multiplicities(self, n_sites: int) -> np.ndarray:
        counts = self._counts
        out = np.zeros(n_sites, dtype=int)
        out[:min(n_sites, len(counts))] = counts[:n_sites]
        return out

    def indices_of_site(self, site_index: int) -> np.ndarray:
        groups = self._groups
        if 0 <= site_index < len(groups):
            return groups[site_index]
        return np.zeros(0, dtype=int)

    # Both lookups are asked for once per row of the site table, and
    # scanning the whole cell for each of them makes drawing that table
    # quadratic in the number of sites -- which a P1 structure with a
    # thousand of them notices.  Grouped once, on first use.

    @property
    def _counts(self) -> np.ndarray:
        counts = self._index.get("counts")
        if counts is None:
            counts = np.bincount(self.site_idx) if len(self.site_idx) \
                else np.zeros(0, dtype=int)
            self._index["counts"] = counts
        return counts

    @property
    def _groups(self) -> list:
        groups = self._index.get("groups")
        if groups is None:
            order = np.argsort(self.site_idx, kind="stable")
            bounds = np.cumsum(self._counts)[:-1]
            groups = np.split(order, bounds) if len(order) else []
            self._index["groups"] = groups
        return groups

    def orbit_of(self, atom_index: int) -> np.ndarray:
        """Indices of every atom generated by the same parent site --
        the atoms that must move together under symmetry."""
        return self.indices_of_site(int(self.site_idx[atom_index]))


# ======================================================================
#  EXPANSION
# ======================================================================

def _wrap(frac: np.ndarray) -> np.ndarray:
    """Fold into [0,1), pulling values that land on 1.0 by rounding
    back to 0.0."""
    w = np.mod(frac, 1.0)
    return np.where(np.abs(w - 1.0) < 1e-12, 0.0, w)


def _min_image_distance(a, b, lattice: Lattice) -> float:
    d = np.asarray(a) - np.asarray(b)
    d -= np.round(d)
    return float(np.linalg.norm(d @ lattice.matrix))


def expand(structure, tol: float = SPECIAL_POSITION_TOL) -> P1Cell:
    """Generate the unit cell of ``structure``.

    Result is memoised on the structure until its next mutation, so
    callers may treat this as cheap.
    """
    return structure.cached(
        f"p1:{tol}", lambda: _expand_uncached(structure, tol))


def _expand_uncached(structure, tol: float) -> P1Cell:
    """Every site through every operation, in one pass.

    Written as array work rather than as a loop over sites because it
    is on the path of every geometry change: the atoms move, the
    expansion is stale, and it is recomputed before anything can be
    drawn.  A loop costs about eight microseconds a site, which is
    nothing for the two sites of rutile and is forty milliseconds --
    per frame -- for a five-thousand-site cell in P1.

    The coincidence test is the part that cannot be done for every site
    at once: it compares every image of a site with every other, and
    holding that for all sites and all operations at the same time is
    a site count times an operation count *squared*.  It is also the
    part that has nothing to do in P1, where one operation cannot
    produce a coincidence -- which is exactly the case with the site
    counts large enough to matter.
    """
    ops = structure.space_group.operations
    lattice = structure.lattice
    n_sites, n_ops = len(structure.sites), len(ops)
    if not n_sites:
        return _empty_cell(lattice)

    frac = np.array([s.frac for s in structure.sites], dtype=float)
    rot = np.array([op.rot for op in ops], dtype=float)
    trans = np.array([op.trans for op in ops], dtype=float)

    # (n_sites, n_ops, 3): site s through operation o.  SymOp.apply is
    # `frac @ rot.T + trans`, and this is that, batched both ways.
    raw = np.einsum("sj,oij->soi", frac, rot) + trans
    wrapped = _wrap(raw)
    tau = np.round(wrapped - raw).astype(int)

    if n_ops == 1:
        keep = np.ones((n_sites, 1), dtype=bool)
    else:
        keep = np.zeros((n_sites, n_ops), dtype=bool)
        for i in range(n_sites):
            keep[i, _distinct(wrapped[i], lattice, tol)] = True

    site_idx, op_idx = np.nonzero(keep)     # site-major, as before
    return P1Cell(
        lattice=lattice,
        frac=wrapped[site_idx, op_idx],
        site_idx=site_idx.astype(int),
        op_idx=op_idx.astype(int),
        tau=tau[site_idx, op_idx],
        elements=tuple(structure.sites[i].element for i in site_idx),
        occupancy=np.array([structure.sites[i].occupancy
                            for i in site_idx], dtype=float),
        labels=tuple(structure.sites[i].label for i in site_idx),
    )


def _empty_cell(lattice) -> P1Cell:
    return P1Cell(
        lattice=lattice,
        frac=np.zeros((0, 3)),
        site_idx=np.zeros(0, dtype=int),
        op_idx=np.zeros(0, dtype=int),
        tau=np.zeros((0, 3), dtype=int),
        elements=(),
        occupancy=np.zeros(0),
        labels=(),
    )


def _distinct(wrapped: np.ndarray, lattice: Lattice,
              tol: float) -> list[int]:
    """Which images of one site are genuinely different atoms.

    A site on a special position is sent to the same point by several
    operations, and each coincidence has to be dropped exactly once --
    the multiplicity of Si in quartz is 3, not 6, and getting this
    wrong doubles the atoms in the cell.  ``tol`` decides what "the
    same point" means and is not floating-point slack; see
    :data:`SPECIAL_POSITION_TOL`.

    The coincidences are transitive at the edges -- three images spread
    over slightly more than ``tol`` -- so the first-wins sweep below
    keeps whichever the earlier operation reached and lets the rest
    fall to it, rather than trying to partition them.

    The first operation to reach a point wins, which is what makes the
    stored ``op_idx`` reproducible.  All the distances are computed at
    once: a group like Fm-3m has 192 operations, and comparing every
    new image against every kept one in Python is tens of thousands of
    scalar distances per site -- on every single edit, because this is
    recomputed whenever the structure changes.
    """
    n = len(wrapped)
    if n < 2:
        return list(range(n))
    d = wrapped[:, None, :] - wrapped[None, :, :]
    d -= np.round(d)
    close = np.linalg.norm(d @ lattice.matrix, axis=2) < tol

    keep: list[int] = []
    taken = np.zeros(n, dtype=bool)
    for k in range(n):
        if taken[k]:
            continue
        keep.append(k)
        taken |= close[k]           # close[k, k] is always True
    return keep


# ======================================================================
#  MAPPING AN EDIT BACK ONTO ITS PARENT
# ======================================================================

def parent_coordinates(structure, cell: P1Cell, atom_index: int,
                       new_frac) -> np.ndarray:
    """Where the parent site must move so that image ``atom_index``
    ends up at ``new_frac``.

    Inverts ``y = R x + t + tau`` for x.  This is the whole mechanism
    behind symmetry-aware dragging: the user moves an image, the parent
    moves, and every other image follows on the next expansion.
    """
    op = structure.space_group.operations[int(cell.op_idx[atom_index])]
    y = np.asarray(new_frac, dtype=float).reshape(3)
    shifted = y - op.trans - cell.tau[atom_index]
    return np.linalg.inv(op.rot) @ shifted


def image_transform(structure, cell: P1Cell, atom_index: int):
    """The (rot, trans) taking parent fractional coordinates to this
    image, including the lattice shift.  Handy for transforming a
    displacement rather than a position."""
    op = structure.space_group.operations[int(cell.op_idx[atom_index])]
    return op.rot, op.trans + cell.tau[atom_index]


def parent_frac(structure, cell: P1Cell, frac) -> np.ndarray:
    """The asymmetric unit that regenerates a whole cell of positions.

    The inverse of an expansion, and the way a *frame* -- a trajectory
    written as the P1 cell, which is what every other program reads --
    is played back against a structure that is not in P1.  Each site is
    read from the first image it generated, through the operation that
    generated it; the other images of that site are not consulted,
    because a frame that broke the symmetry could not be represented by
    an asymmetric unit at all and averaging would hide that rather than
    say it.

    ``frac`` is ``(cell.n_atoms, 3)``; the answer is ``(n_sites, 3)``.
    """
    frac = np.asarray(frac, dtype=float).reshape(-1, 3)
    if len(frac) != cell.n_atoms:
        raise ValueError(
            f"expected {cell.n_atoms} positions, one per atom of the "
            f"cell, and got {len(frac)}")
    out = np.zeros((structure.n_sites, 3))
    for index in range(structure.n_sites):
        images = cell.indices_of_site(index)
        if not len(images):
            continue
        first = int(images[0])
        out[index] = parent_coordinates(structure, cell, first,
                                        frac[first])
    return out
