"""
xtal.core.p1
============
Expanding an asymmetric unit into the full contents of the unit cell.

A :class:`P1Cell` is *derived* data -- it is never edited directly and
never stored in a document.  What makes it more than a list of
coordinates is the provenance it carries for every atom:

    frac[k] = ops[op_idx[k]].apply(sites[site_idx[k]].frac) + tau[k]

That triple (parent site, operation, lattice shift) is what lets the
application do the two things a symmetry-aware editor must do:

* draw a symmetry image and know which asymmetric site it belongs to
  when the user clicks it;
* take a *new* position for an image atom and map it back through the
  inverse operation onto the parent site, so the whole orbit moves
  together (:func:`parent_coordinates`).

Atoms that coincide -- an atom on a special position, where several
operations produce the same point -- are generated once.  The number of
survivors from one site is its multiplicity.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from xtal.core.lattice import Lattice

# Two generated positions closer than this (in Angstrom) are the same
# atom on a special position.  Small on purpose: at this stage the
# coordinates come from exact symmetry operations, so the only spread
# is floating-point noise.  User-facing duplicate merging, which has to
# cope with sloppy experimental coordinates, is a separate operation
# with its own, larger tolerance.
SPECIAL_POSITION_TOL = 1e-3


@dataclass(frozen=True)
class P1Cell:
    """Every atom of the unit cell, with its symmetry provenance."""

    lattice: Lattice
    frac: np.ndarray                # (N,3) in [0,1)
    site_idx: np.ndarray            # (N,) parent site index
    op_idx: np.ndarray              # (N,) operation index
    tau: np.ndarray                 # (N,3) int lattice shift
    elements: tuple[str, ...]
    occupancy: np.ndarray           # (N,)
    labels: tuple[str, ...]

    @property
    def n_atoms(self) -> int:
        return len(self.frac)

    def __len__(self) -> int:
        return len(self.frac)

    @property
    def cart(self) -> np.ndarray:
        return self.lattice.to_cart(self.frac)

    @property
    def numbers(self) -> np.ndarray:
        from xtal.core import elements as el
        return np.array([el.atomic_number(s) for s in self.elements])

    def multiplicity(self, site_index: int) -> int:
        """How many atoms this asymmetric site generates."""
        return int(np.count_nonzero(self.site_idx == site_index))

    def multiplicities(self, n_sites: int) -> np.ndarray:
        return np.array([self.multiplicity(i) for i in range(n_sites)])

    def indices_of_site(self, site_index: int) -> np.ndarray:
        return np.flatnonzero(self.site_idx == site_index)

    def orbit_of(self, atom_index: int) -> np.ndarray:
        """Indices of every atom generated by the same parent site --
        the atoms that must move together under symmetry."""
        return self.indices_of_site(int(self.site_idx[atom_index]))


# ======================================================================
#  EXPANSION
# ======================================================================

def _wrap(frac: np.ndarray) -> np.ndarray:
    """Fold into [0,1), pulling values that land on 1.0 by rounding
    back to 0.0."""
    w = np.mod(frac, 1.0)
    return np.where(np.abs(w - 1.0) < 1e-12, 0.0, w)


def _min_image_distance(a, b, lattice: Lattice) -> float:
    d = np.asarray(a) - np.asarray(b)
    d -= np.round(d)
    return float(np.linalg.norm(d @ lattice.matrix))


def expand(structure, tol: float = SPECIAL_POSITION_TOL) -> P1Cell:
    """Generate the unit cell of ``structure``.

    Result is memoised on the structure until its next mutation, so
    callers may treat this as cheap.
    """
    return structure.cached(
        f"p1:{tol}", lambda: _expand_uncached(structure, tol))


def _expand_uncached(structure, tol: float) -> P1Cell:
    ops = structure.space_group.operations
    lattice = structure.lattice
    fracs, site_idx, op_idx, taus = [], [], [], []
    elements, occ, labels = [], [], []

    for i, site in enumerate(structure.sites):
        kept: list[np.ndarray] = []
        for k, op in enumerate(ops):
            raw = op.apply(site.frac)
            wrapped = _wrap(raw)
            if any(_min_image_distance(wrapped, other, lattice) < tol
                   for other in kept):
                continue                    # special position, already
            kept.append(wrapped)
            fracs.append(wrapped)
            site_idx.append(i)
            op_idx.append(k)
            taus.append(np.round(wrapped - raw).astype(int))
            elements.append(site.element)
            occ.append(site.occupancy)
            labels.append(site.label)

    n = len(fracs)
    return P1Cell(
        lattice=lattice,
        frac=np.array(fracs, dtype=float).reshape(n, 3),
        site_idx=np.array(site_idx, dtype=int),
        op_idx=np.array(op_idx, dtype=int),
        tau=np.array(taus, dtype=int).reshape(n, 3),
        elements=tuple(elements),
        occupancy=np.array(occ, dtype=float),
        labels=tuple(labels),
    )


# ======================================================================
#  MAPPING AN EDIT BACK ONTO ITS PARENT
# ======================================================================

def parent_coordinates(structure, cell: P1Cell, atom_index: int,
                       new_frac) -> np.ndarray:
    """Where the parent site must move so that image ``atom_index``
    ends up at ``new_frac``.

    Inverts ``y = R x + t + tau`` for x.  This is the whole mechanism
    behind symmetry-aware dragging: the user moves an image, the parent
    moves, and every other image follows on the next expansion.
    """
    op = structure.space_group.operations[int(cell.op_idx[atom_index])]
    y = np.asarray(new_frac, dtype=float).reshape(3)
    shifted = y - op.trans - cell.tau[atom_index]
    return np.linalg.inv(op.rot) @ shifted


def image_transform(structure, cell: P1Cell, atom_index: int):
    """The (rot, trans) taking parent fractional coordinates to this
    image, including the lattice shift.  Handy for transforming a
    displacement rather than a position."""
    op = structure.space_group.operations[int(cell.op_idx[atom_index])]
    return op.rot, op.trans + cell.tau[atom_index]
