"""
xtal.core.subgroups
===================
Descending to a maximal subgroup: computing the subgroups, and -- the
part that actually costs something -- naming them.

Raising the symmetry of a structure is a *measurement*: spglib looks at
the coordinates and reports what it finds, and there is one answer.
Lowering it is a **choice**.  A group has several maximal subgroups,
each of which splits a different orbit into independent pieces, and
picking one is the first step of every distortion model, every ordering
model and every displacive phase transition.  So this module's job is
to lay out the choices, say what each one costs, and hand back
something the rest of the application can apply.

Two kinds are offered, and which half of the group is given up is the
difference between them.  A **translationengleiche** subgroup keeps
every translation and drops rotations; a **klassengleiche** one keeps
the rotations and drops translations.  Of the second kind only the
descents that give up part of the **centring** are here, because those
are the ones that happen in the same cell and so need no table: Fm-3m
contains Pm-3m as a genuine subset of its operations, at index 4, in
the same cubic cell, and rock salt descended that way is the
cation-ordering model.  A klassengleiche subgroup on a genuinely
larger cell is a superstructure, wants Bilbao's tables or a walk over
the sublattices, and is not offered yet.

Two halves, and the second is the hard one:

**Finding them** is a subgroup-lattice walk over the operations reduced
modulo the lattice centring.  The reduction is not an optimisation, it
is what makes the problem finite in practice -- Fm-3m has 192
operations and 48 once the centring is divided out, and the difference
between closing subsets of 48 and of 192 is the difference between
instant and hopeless.  The walk starts from the cyclic subgroups and
repeatedly adjoins one more operation, which finds every subgroup
regardless of how many generators it needs; the familiar "every
crystallographic point group is generated by at most three elements"
shortcut is neither used nor relied on.

The centring is then put *back*, rather than never having been taken
out.  For each subgroup of the reduced group, and each subgroup of the
centring group that it leaves invariant, the reduced generators are
lifted through the choices of translation available to them and
closed.  Which choices close is not a formality -- it is the whole of
the klassengleiche half, and it is what separates Pm-3m from Pn-3m.
There are a few dozen such closures over sets of at most 192 elements,
which is a different thing from walking the subgroup lattice of 192.

**Naming them** is the work this module exists for.  The operations
come out in the *parent's* basis, and most subgroups are not in their
standard setting there: asking gemmi to recognise the raw operation
list names about 11 of the 27 maximal subgroups of the four structures
in the test suite and returns nothing for the rest -- and among the
nameless ones sits, for rutile, the only descent that splits anything.
A subgroup that can only be offered as a list of operations is not
something anyone can choose from.

The way out is to build a crystal that *has* the subgroup as its
symmetry and ask spglib to identify it, because spglib answers with the
transformation to the standard setting as well as the name.  Two
generic points, of two different species, are given the orbit of the
candidate operation set in a cell of the parent's shape.  A generic
point has trivial site symmetry, so the orbit's symmetry is exactly the
group that generated it -- with one caveat that the second species is
there to cover: a *single* orbit can acquire an accidental inversion
centre about its own centroid, which is how a naive version of this
names P4_2nm as P4_2/mnm.  Two unrelated points cannot both acquire the
same accidental operation.

Every answer is checked: spglib has to report exactly as many
operations as were asked about, or the candidate is returned unnamed
rather than mislabelled.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from functools import lru_cache

import numpy as np
import spglib

from xtal.core.lattice import Lattice
from xtal.core.spacegroup import SpaceGroup, SymOp

# Operations are held as integers here, not floats: a subgroup is
# decided by exact equality of translations like 1/3 and 1/4, and
# 1/3 is not a float.  Twenty-four covers every translation a space
# group has, and this is six times that because a translation
# re-expressed on a sublattice is divided by the sublattice's index --
# so a sixth of a cell described on a cell three times larger wants a
# denominator of 72, and nothing here should be one factor from wrong.
# Every conversion checks that it landed exactly (:func:`_exact`).
DEN = 144
IDENTITY_ROT = (1, 0, 0, 0, 1, 0, 0, 0, 1)

# Two points with no site symmetry, unrelated to each other and to any
# special position.  Their orbits are the crystal whose symmetry spglib
# is asked to name.
PROBE_POINTS = (
    (0.1234567, 0.2345678, 0.3456789),
    (0.4271839, 0.0937261, 0.1783952),
)

# The shape of the cell the probe crystal is built in.  Only the
# *metric symmetry* matters, so these are deliberately generic numbers
# put through the parent group's own cell constraint: a group whose
# subgroups are being named must not be handed a cell with more metric
# symmetry than it has, or the naming inherits symmetry the structure
# never had.
PROBE_PARAMETERS = (5.1, 6.3, 7.7, 83.0, 97.0, 113.0)

NAMING_SYMPREC = 1e-5


# ======================================================================
#  A SUBGROUP
# ======================================================================

@dataclass(frozen=True)
class Subgroup:
    """One subgroup of a space group, up to conjugacy.

    ``ops`` is in the **parent's** basis, which is where it was found --
    except where ``sublattice`` says otherwise.  A subgroup whose
    translation lattice is a sublattice of the parent's cannot be
    written in the parent's cell at all, because a list held modulo the
    parent's translations puts back the ones the child gave up; those
    carry their operations in the cell ``sublattice`` names, whose rows
    are its translation vectors in the parent's units.
    ``group`` is the same set of operations named in its own standard
    setting, and ``basis``/``origin_shift`` are how to get there:

        new lattice rows = basis @ old lattice rows
        x_new            = (x_old - origin_shift_old) @ inv(basis)

    For a good half of all subgroups the basis is the identity and the
    shift is zero, which is the case the descent costs nothing at all:
    not one atom moves and the cell is untouched.
    """

    index: int
    ops: tuple[SymOp, ...]
    group: SpaceGroup | None
    basis: np.ndarray                  # (3,3), rows = new vectors
    origin_shift: np.ndarray           # (3,) in the parent's basis
    maximal: bool = True
    n_conjugates: int = 1
    k_index: int = 1                   # lattice translations lost
    sublattice: np.ndarray | None = None    # None means the same cell
    _cache: dict = field(default_factory=dict, repr=False,
                         compare=False)

    @property
    def named(self) -> bool:
        return self.group is not None

    @property
    def t_index(self) -> int:
        """How much of the *point* group is lost.  The total index is
        this times :attr:`k_index`, and the two are independent."""
        return self.index // self.k_index

    @property
    def kind(self) -> str:
        """``t``, ``k`` or ``t + k``.

        Not decoration: a group can appear twice in one list at two
        different indices, once as a translationengleiche descent and
        once as a klassengleiche one, and without this the two rows are
        the same row with a different number in it.
        """
        if self.k_index == 1:
            return "t"
        return "k" if self.t_index == 1 else "t + k"

    @property
    def symbol(self) -> str:
        return self.group.short_name if self.group else "unnamed"

    @property
    def order(self) -> int:
        return len(self.ops)

    @property
    def keeps_the_cell(self) -> bool:
        """True when adopting this subgroup moves nothing: same basis,
        same origin, same coordinates, only fewer operations."""
        return (np.allclose(self.basis, np.eye(3), atol=1e-9)
                and np.allclose(self.origin_shift, 0.0, atol=1e-9))

    @property
    def enlarges_the_lattice(self) -> bool:
        """True when the child has fewer *lattice translations* than
        the parent, so its cell has to grow -- a superstructure.

        Not the same question as :attr:`volume_ratio` being above one.
        A subgroup can keep every translation and still be named in a
        larger conventional cell, which is what the rhombohedral and
        monoclinic settings do, and calling that a superstructure would
        be calling a change of axes a change of crystal.
        """
        return self.sublattice is not None

    @property
    def cell_ratio(self) -> float:
        """Volume of the child's conventional cell over the cell its
        operations are counted in.  The same as :attr:`volume_ratio`
        unless the child sits on a sublattice."""
        if self.sublattice is None:
            return self.volume_ratio
        return self.volume_ratio / abs(float(np.linalg.det(
            self.sublattice)))

    @property
    def volume_ratio(self) -> float:
        """Volume of the subgroup's conventional cell, over the
        parent's.  A translationengleiche subgroup keeps the lattice,
        but its *conventional* cell can be a different multiple of the
        primitive one -- the rhombohedral subgroups of a cubic group
        are the usual case, at three times the volume."""
        return abs(float(np.linalg.det(self.basis)))

    def describe(self) -> str:
        where = ("same cell and origin" if self.keeps_the_cell
                 else "new setting")
        return (f"{self.symbol} (#{self.group.number}), index "
                f"{self.index} ({self.kind}), {where}" if self.group
                else f"unnamed, index {self.index} ({self.kind})")

    def __repr__(self) -> str:
        return f"Subgroup({self.symbol}, index {self.index})"


# ======================================================================
#  INTEGER OPERATIONS
# ======================================================================
#
#  An operation is (rot, tran): nine ints and three ints over DEN.
#  Composition and comparison are exact, which is the whole point.

def _int_ops(group: SpaceGroup):
    out = []
    for op in group.operations:
        rot = tuple(int(round(v)) for v in np.asarray(op.rot).reshape(9))
        tran = tuple(int(round(v * DEN)) % DEN for v in op.trans)
        out.append((rot, tran))
    return out


def _compose(a, b):
    ra, ta = a
    rb, tb = b
    rot = tuple(sum(ra[3 * i + k] * rb[3 * k + j] for k in range(3))
                for i in range(3) for j in range(3))
    tran = tuple((sum(ra[3 * i + k] * tb[k] for k in range(3)) + ta[i])
                 % DEN for i in range(3))
    return rot, tran


def _centrings(ops) -> list:
    """The pure lattice translations in the operation list."""
    return [tran for rot, tran in ops if rot == IDENTITY_ROT]


def _canonical(op, centrings):
    """The operation's representative modulo the centring translations.

    Two operations that differ by a centring translation are the same
    operation of the group *modulo the lattice*, and a
    translationengleiche subgroup either contains both or neither --
    which is why the walk below can work on the representatives alone.
    A klassengleiche subgroup contains one and not the other, and that
    is exactly the distinction :func:`_lifts` puts back afterwards.
    """
    rot, tran = op
    return rot, min(tuple((tran[i] + c[i]) % DEN for i in range(3))
                    for c in centrings)


def _reduced(group: SpaceGroup):
    """:func:`_reduced_ops` for a named group."""
    return _reduced_ops(_int_ops(group))


def _reduced_ops(ops):
    """(representatives, centrings): the operations modulo their own
    lattice translations, with the identity first in both lists.

    Both orders are load-bearing further down: an operation of the whole
    group is addressed as ``rep_index * len(centrings) + centring_index``
    and the closure below wants the identity of that numbering to be
    zero.
    """
    centrings = _centrings(ops)
    zero = (0, 0, 0)
    centrings = [zero] + [c for c in centrings if c != zero]
    identity = _canonical((IDENTITY_ROT, zero), centrings)
    reps = sorted({_canonical(op, centrings) for op in ops})
    reps.remove(identity)
    return [identity] + reps, centrings


def _multiplication_table(reps, centrings):
    """``table[i][j]`` is the index of ``rep_i . rep_j``.

    Every closure below is then integer bookkeeping over indices, which
    is what turns Fm-3m's enumeration from half a minute into a tenth
    of a second.
    """
    where = {op: i for i, op in enumerate(reps)}
    return [[where[_canonical(_compose(reps[i], reps[j]), centrings)]
             for j in range(len(reps))] for i in range(len(reps))]


def _close(seed, table) -> frozenset:
    """The subgroup generated by ``seed`` (indices into the table)."""
    elements = set(seed)
    elements.add(0)
    frontier = list(elements)
    generators = sorted(elements)
    while frontier:
        fresh = []
        for x in frontier:
            row = table[x]
            for g in generators:
                y = row[g]
                if y not in elements:
                    elements.add(y)
                    fresh.append(y)
        frontier = fresh
    return frozenset(elements)


def _all_subgroups(reps, table) -> set:
    """Every proper subgroup, as a frozenset of indices.

    Walks the subgroup lattice upwards from the cyclic subgroups: start
    with what one element generates, then repeatedly adjoin one more
    operation to everything found so far.  Slower than trying every
    subset of three elements and correct without assuming a bound on
    the number of generators -- a bound that holds for the point groups
    this walk runs over and stops holding the moment the centring
    translations are back in the set, which is where :func:`_lifts`
    picks the problem up.

    The trivial subgroup is one of the answers: dropping every rotation
    and keeping only the lattice is a descent like any other, and it is
    the one the rest of the application calls Reduce to P1.
    """
    n = len(reps)
    found: set = {frozenset({0})}
    frontier: set = set()
    for g in range(1, n):
        h = _close([g], table)
        if len(h) < n and h not in found:
            found.add(h)
            frontier.add(h)
    while frontier:
        grown = set()
        for h in frontier:
            for g in range(1, n):
                if g in h:
                    continue
                k = _close(h | {g}, table)
                if len(k) < n and k not in found:
                    found.add(k)
                    grown.add(k)
        frontier = grown
    return found


def _inverses(table) -> list:
    """``inv[g]`` is the index of the inverse of operation ``g``."""
    return [next(m for m in range(len(table)) if row[m] == 0)
            for row in table]


def _conjugacy_classes(table, found) -> list:
    """Group the subgroups into conjugacy classes under the parent.

    **Conjugate subgroups are the same descent.**  Fm-3m's three
    tetragonal subgroups differ only in which cubic axis they keep, and
    the parent's own three-fold carries any one of them onto any other
    -- so a structure that has Fm-3m as its symmetry comes out of all
    three as the same crystal, in the same group and the same cell.

    Not with the same coordinates, and the difference is worth being
    exact about: the three results are related by an operation of the
    parent, so they sit at different origins and on different axes
    inside that cell.  They are congruent, not identical -- an
    equivalent setting of one structure rather than three structures.
    Which of the equivalent settings you get is the parent's choice of
    axes and not a decision anybody can make usefully, so offering it
    as a choice is worse than not offering it: the orientation only
    becomes real once a distortion has been applied, and then it is the
    distortion that carries it and not this list.

    Returns ``(representative, size)`` per class, with a deterministic
    representative so the list does not reshuffle between runs.
    """
    inv = _inverses(table)
    classes, seen = [], set()
    for h in sorted(found, key=lambda s: (len(s), sorted(s))):
        if h in seen:
            continue
        orbit = set()
        for g in range(len(table)):
            gi = inv[g]
            orbit.add(frozenset(table[table[g][k]][gi] for k in h))
        seen |= orbit
        classes.append((min(orbit, key=sorted), len(orbit)))
    return classes


def _ops_from_full(indices, reps, centrings) -> list:
    """A subgroup, held as indices into the whole group, back into
    operations.  Operation ``i * len(centrings) + a`` is ``rep_i``
    translated by the ``a``-th centring vector."""
    c = len(centrings)
    out = []
    for x in sorted(indices):
        rot, tran = reps[x // c]
        vector = centrings[x % c]
        out.append((rot, tuple((tran[k] + vector[k]) % DEN
                               for k in range(3))))
    return out


# ======================================================================
#  THE CENTRING GROUP
# ======================================================================
#
#  A translationengleiche subgroup keeps every centring translation; a
#  klassengleiche one keeps only some of them.  So the centring has to
#  be enumerated in its own right -- and it is tiny, four elements for
#  F and two or three for everything else, which is exactly why this
#  half is affordable while the reduction stays in place.


def _centring_sum_table(centrings) -> list:
    """``cadd[a][b]`` is the index of ``c_a + c_b``: the centring
    vectors are a group under addition modulo the lattice."""
    where = {c: i for i, c in enumerate(centrings)}
    return [[where[tuple((a[k] + b[k]) % DEN for k in range(3))]
             for b in centrings] for a in centrings]


def _centring_subgroups(centrings, cadd) -> list:
    """Every subgroup of the centring group.  Four elements at most, so
    every subset is tried and the ones that close are kept."""
    n = len(centrings)
    out = []
    for mask in range(1, 1 << n):
        members = frozenset(i for i in range(n) if mask >> i & 1)
        if 0 not in members:
            continue
        if all(cadd[a][b] in members
               for a in members for b in members):
            out.append(members)
    return out


def _rotation_action(reps, centrings) -> list:
    """``action[i][b]``: where the rotation of ``rep_i`` sends ``c_b``.

    Always another centring vector.  That the centring group is
    invariant under every rotation of the space group is what makes the
    centring a property of the *lattice*, and it is also the test a
    candidate subgroup of it has to pass before it can be the
    translation part of anything.
    """
    where = {c: i for i, c in enumerate(centrings)}
    out = []
    for rot, _tran in reps:
        out.append([where[tuple(
            sum(rot[3 * i + k] * c[k] for k in range(3)) % DEN
            for i in range(3))] for c in centrings])
    return out


def _coset_offsets(reps, table, centrings) -> list:
    """``offset[i][j]``: the centring vector by which ``rep_i . rep_j``
    exceeds the canonical representative it reduces to."""
    where = {c: i for i, c in enumerate(centrings)}
    out = []
    for i in range(len(reps)):
        row = []
        for j in range(len(reps)):
            _rot, tran = _compose(reps[i], reps[j])
            _canon_rot, canon_tran = reps[table[i][j]]
            row.append(where[tuple((tran[k] - canon_tran[k]) % DEN
                                   for k in range(3))])
        out.append(row)
    return out


def _full_table(reps, table, centrings) -> list:
    """The multiplication table of the *whole* group.

    Assembled from the reduced table and the centring bookkeeping
    rather than by composing 192 pairs of operations directly: the
    reduction is still doing the work, and what is added on top is
    integer arithmetic over four vectors.  Written out, the product of
    ``(R_i, t_i + c_a)`` and ``(R_j, t_j + c_b)`` is ``(R_i R_j,
    t_i + R_i t_j + R_i c_b + c_a)``, and the first two terms are what
    the reduced table already knows.
    """
    c = len(centrings)
    if c == 1:
        return [row[:] for row in table]
    cadd = _centring_sum_table(centrings)
    action = _rotation_action(reps, centrings)
    offset = _coset_offsets(reps, table, centrings)
    out = []
    for i in range(len(reps)):
        for a in range(c):
            row = []
            for j in range(len(reps)):
                base = table[i][j] * c
                shift = offset[i][j]
                for b in range(c):
                    row.append(base + cadd[shift][cadd[action[i][b]][a]])
            out.append(row)
    return out


# ======================================================================
#  A LARGER CELL
# ======================================================================
#
#  The klassengleiche subgroups that do not fit in the parent's cell.
#  Their translation lattice is a *sublattice* of the parent's, so the
#  conventional cell grows -- and the operations then cannot be written
#  in the parent's cell at all, because an operation list held modulo
#  the parent's translations puts back the very translations the child
#  has given up.  Everything below therefore works in the child's own
#  primitive cell, which is also the only cell the naming probe can be
#  built in: built in the parent's, the probe crystal gets the parent's
#  translations for free and is named as the parent.
#
#  Two bounds, and both are forced rather than chosen.
#
#  **Maximal sublattices only.**  One with another invariant sublattice
#  strictly between it and the parent's carries a subgroup that is not
#  maximal, and the group in between is offered in its own right.  This
#  is not the same as a prime index: an fcc lattice has no invariant
#  sublattice of index two or three at all, so its maximal ones are at
#  index four, and a bound written as "prime" would have found none of
#  them.
#
#  **The child must not be the parent's own group.**  A subgroup
#  isomorphic to its parent -- the same group on a larger cell -- exists
#  at every prime index for most lattices, so that family is infinite
#  and cannot be listed; International Tables gives it as a formula in
#  p rather than as rows, and so must anything else.  What is left is
#  finite, and searching every space group over sublattice indices up
#  to nine finds none of it above four, which is why the search stops
#  there.
#
#  The "every subgroup, not only the maximal ones" of the same-cell
#  half deliberately does not extend here.

SUBLATTICE_INDICES = (2, 3, 4)


def _exact(values, den: int = DEN):
    """``values`` as integers over ``den``, or None if they are not.

    A translation re-expressed on a sublattice is divided by that
    sublattice's index, and a denominator the integer representation
    cannot hold would be silently rounded into a different operation.
    Returning None makes the whole sublattice be skipped instead.
    """
    scaled = np.asarray(values, dtype=float) * den
    snapped = np.round(scaled)
    if np.any(np.abs(scaled - snapped) > 1e-6):
        return None
    return snapped.astype(int)


def _row_hnf(rows) -> np.ndarray:
    """Three vectors spanning the same lattice as the integer ``rows``.

    Integer Gaussian elimination, one column at a time: subtract the
    smallest non-zero entry in the column from the others until only
    one is left, which is Euclid's algorithm run on whole rows.  Used
    to turn the parent's translations -- three cell vectors and however
    many centrings -- back into three.
    """
    work = [[int(v) for v in row] for row in rows]
    basis = []
    for column in range(3):
        while True:
            live = [r for r in work if r[column] != 0]
            if len(live) <= 1:
                break
            live.sort(key=lambda r: abs(r[column]))
            pivot = live[0]
            for row in live[1:]:
                factor = row[column] // pivot[column]
                for k in range(3):
                    row[k] -= factor * pivot[k]
        live = [r for r in work if r[column] != 0]
        if not live:
            continue
        pivot = live[0]
        if pivot[column] < 0:
            pivot = [-v for v in pivot]
        basis.append(pivot)
        work = [r for r in work if r is not live[0]]
    if len(basis) != 3:
        raise ValueError("the translations do not span three dimensions")
    return np.array(basis, dtype=int)


def _primitive_basis(centrings) -> np.ndarray:
    """Rows: a basis of the parent's whole translation lattice, in the
    parent cell's own units.  The identity for a primitive group, and
    the primitive cell of an F, I, C or R one."""
    if len(centrings) == 1:
        return np.eye(3)
    rows = [[DEN if i == j else 0 for j in range(3)] for i in range(3)]
    rows += [list(c) for c in centrings]
    return _row_hnf(rows) / float(DEN)


def _hermite_forms(n: int) -> list:
    """Every sublattice of index ``n``, as rows in the basis it is a
    sublattice of.

    One per matrix in Hermite normal form with that determinant, which
    is the standard enumeration and is complete: lower triangular, and
    each entry below the diagonal reduced modulo the diagonal of its
    own column.  For a prime that comes to ``p * p + p + 1``, the
    number of lines in the plane over Z/p.
    """
    out = []
    for d1 in range(1, n + 1):
        if n % d1:
            continue
        for d2 in range(1, n // d1 + 1):
            if (n // d1) % d2:
                continue
            d3 = n // (d1 * d2)
            for h21 in range(d1):
                for h31 in range(d1):
                    for h32 in range(d2):
                        out.append(np.array(
                            [[d1, 0, 0], [h21, d2, 0], [h31, h32, d3]],
                            dtype=int))
    return out


def _invariant_sublattices(reps, centrings) -> list:
    """``(basis, index)`` for every sublattice of the parent's
    translations, of prime index, that each of its rotations maps onto
    itself.

    A sublattice the point group does not preserve cannot be the
    translation lattice of a subgroup that keeps the point group: the
    rotations would carry a translation out of the set.

    Only the **maximal** ones are kept: one with another invariant
    sublattice strictly between it and the parent carries a subgroup
    that is not maximal either, and the group in between is offered in
    its own right.

    One that still **contains the parent cell's own lattice** is thrown
    away too, and for a different reason: the same-cell pass works
    modulo that lattice, so every subgroup holding it has already been
    found there and described in the parent's own axes.  Without this,
    a C-centred parent offers each of its lost-centring descents twice
    -- once as itself and once on a sheared basis for the same lattice,
    giving the same group, the same cell and the same crystal.  The
    maximality test runs first and over *every* invariant sublattice,
    including those: a sublattice whose only invariant superlattice is
    the parent's own cell is genuinely not maximal.
    """
    primitive = _primitive_basis(centrings)
    rotations = [np.array(rot, dtype=float).reshape(3, 3)
                 for rot, _tran in reps]
    invariant = []
    for index in SUBLATTICE_INDICES:
        for form in _hermite_forms(index):
            basis = form @ primitive
            inverse = np.linalg.inv(basis)
            if all(_exact(inverse.T @ rot @ basis.T, 1) is not None
                   for rot in rotations):
                invariant.append((basis, index))
    out = []
    for basis, index in invariant:
        inverse = np.linalg.inv(basis)
        if any(other_index < index
               and _exact(basis @ np.linalg.inv(other), 1) is not None
               for other, other_index in invariant):
            continue                      # something sits in between
        if _exact(inverse, 1) is not None:
            continue                      # the parent's own lattice
        out.append((basis, index))
    return out


def _cosets_in(basis, centrings) -> list:
    """The parent's translations modulo the sublattice's, as fractions
    of the sublattice's own cell.  One for each unit of the index."""
    inverse = np.linalg.inv(np.asarray(basis, dtype=float))
    seen, out = set(), []
    box = range(-3, 4)
    for i in box:
        for j in box:
            for k in box:
                for centring in centrings:
                    vector = (np.array([i, j, k], dtype=float)
                              + np.array(centring) / DEN)
                    exact = _exact(np.mod(vector @ inverse, 1.0))
                    if exact is None:
                        return []
                    key = tuple(int(v) % DEN for v in exact)
                    if key not in seen:
                        seen.add(key)
                        out.append(key)
    return out


def _ops_in_cell(ops, basis, cosets) -> list:
    """The parent's operations re-expressed on ``basis``.

    Every operation is carried across and then repeated once per coset:
    a translation of the parent that is no longer a translation of this
    cell has become a centring translation of it, and the group in the
    new cell is the old group with those put back in.
    """
    matrix = np.asarray(basis, dtype=float)
    inverse = np.linalg.inv(matrix)
    seen, out = set(), []
    for rot, tran in ops:
        turned = _exact(inverse.T @ np.array(rot, dtype=float).reshape(
            3, 3) @ matrix.T, 1)
        if turned is None:
            return []
        moved = _exact((np.array(tran, dtype=float) / DEN) @ inverse)
        if moved is None:
            return []
        turned = tuple(int(v) for v in turned.reshape(9))
        for coset in cosets:
            shifted = tuple(int(moved[k] + coset[k]) % DEN
                            for k in range(3))
            if (turned, shifted) not in seen:
                seen.add((turned, shifted))
                out.append((turned, shifted))
    return out


def _on_a_sublattice(group, ops, reps, centrings, lattice) -> list:
    """The maximal klassengleiche subgroups whose cell is larger.

    One pass per invariant sublattice.  In that sublattice's own cell
    the parent is a group with the translations it is about to lose
    sitting in it as centrings, and the child is then the subgroup that
    keeps the whole point group and none of them -- which is the same
    lift, closed the same way, as the same-cell half.  What is
    different is only where it is all written down.
    """
    out = []
    for basis, index in _invariant_sublattices(reps, centrings):
        cosets = _cosets_in(basis, centrings)
        if len(cosets) != index:
            continue
        moved = _ops_in_cell(ops, basis, cosets)
        if not moved:
            continue
        cell_reps, cell_centrings = _reduced_ops(moved)
        if len(cell_centrings) != index or len(cell_reps) != len(reps):
            continue
        table = _multiplication_table(cell_reps, cell_centrings)
        ftable = _full_table(cell_reps, table, cell_centrings)
        whole = frozenset(range(len(cell_reps)))
        found = _lifts(whole, frozenset({0}),
                       _generating_set(whole, table), index, ftable)
        if not found:
            continue
        probe = lattice.transform(basis)
        for indices, n_conjugates in _conjugacy_classes(ftable, found):
            child = _ops_from_full(indices, cell_reps, cell_centrings)
            # The whole point group is kept and the translations lost
            # are the sublattice's index, so the index *is* the index.
            candidate = _describe_candidate(
                probe, child, basis, index=index, k_index=index,
                maximal=True, n_conjugates=n_conjugates)
            if not candidate.named:
                # Nothing to offer: it cannot be applied, and it cannot
                # be told apart from the infinite isomorphic family.
                continue
            if candidate.group.number == group.number:
                continue                  # the same group, larger cell
            out.append(candidate)
    return out


def _describe_candidate(lattice, ops, sublattice, index, k_index,
                        maximal, n_conjugates) -> Subgroup:
    """Name an operation list and wrap it up, in whichever cell it was
    found in.  ``sublattice`` is None for the parent's own cell, and
    otherwise composes with the transformation the naming returns --
    the child's standard setting is reached from the parent through the
    sublattice's cell, not directly."""
    named = _name(lattice, ops)
    if named is None:
        basis, shift = np.eye(3), np.zeros(3)
        child = None
    else:
        child, p_matrix, p_shift = named
        # spglib gives x_std = P x + p; the application works in
        # lattice rows and a shift of the origin, so invert it.
        basis = _tidy(np.linalg.inv(p_matrix).T)
        shift = -np.linalg.solve(p_matrix, p_shift)
        if sublattice is not None:
            shift = shift @ sublattice
            basis = _tidy(basis @ sublattice)
        # The origin shift is only defined modulo a lattice
        # translation, and "origin at 0, 0, 1/2" is the form it is
        # written in.
        shift = np.mod(_tidy(shift), 1.0)
        shift = _tidy(np.where(np.abs(shift - 1.0) < 1e-9, 0.0, shift))
    candidate = Subgroup(
        index=index, ops=_to_symops(ops), group=child,
        basis=np.asarray(basis, dtype=float),
        origin_shift=np.asarray(shift, dtype=float),
        maximal=maximal, n_conjugates=n_conjugates, k_index=k_index,
        sublattice=(None if sublattice is None
                    else np.asarray(sublattice, dtype=float)))
    if _reconciles(candidate):
        return candidate
    return Subgroup(index=candidate.index, ops=candidate.ops,
                    group=None, basis=np.eye(3),
                    origin_shift=np.zeros(3), maximal=maximal,
                    n_conjugates=n_conjugates, k_index=k_index,
                    sublattice=candidate.sublattice)


def _generating_set(h, table) -> list:
    """A small generating set for a reduced subgroup, found greedily.

    Three elements always suffice for a crystallographic point group,
    but nothing here leans on that: elements are taken until the
    closure *is* the subgroup, so a fourth is taken when a fourth is
    needed.  The bound is a fact about point groups and this list is
    about to be lifted back into a space group, where it stops being
    one.
    """
    gens: list = []
    have = frozenset({0})
    for g in sorted(h):
        if g in have:
            continue
        gens.append(g)
        have = _close(gens, table)
        if have == h:
            break
    return gens


def _lifts(h, d, gens, c, ftable) -> set:
    """Every subgroup whose operations reduce onto ``h`` and whose
    translations are exactly ``d``.

    The two halves do not determine the subgroup.  Each generator of
    ``h`` can be lifted back through any of the ``c`` translations
    available to it, and which of those choices close into a group is
    the whole of the klassengleiche half -- it is what separates
    Pm-3m from Pn-3m, and offering only one of them would be offering
    the wrong one three times out of four.

    The walk prunes on the two things that only get worse as a closure
    grows: more elements than the subgroup can hold, and a translation
    outside ``d``.  Most branches die on the first generator.
    """
    target = len(h) * len(d)
    out: set = set()

    def walk(k: int, seed) -> None:
        current = _close(seed, ftable)
        if len(current) > target:
            return
        for x in current:
            if x // c == 0 and x % c not in d:
                return
        if k == len(gens):
            if len(current) == target:
                out.add(current)
            return
        for a in range(c):
            walk(k + 1, current | {gens[k] * c + a})

    walk(0, frozenset(d))
    return out


def _all_subgroups_full(found, reps, table, centrings, ftable) -> set:
    """Every proper subgroup of the whole group, as indices into it.

    The reduced walk supplies the point-group half; this pairs each of
    its answers with each subgroup of the centring that the answer
    leaves invariant, and lifts.  Keeping the whole reduced group in
    the list is what produces the descents that lose nothing *but*
    centring -- Fm-3m to Pm-3m -- which are the ones the feature was
    missing.
    """
    c = len(centrings)
    if c == 1:
        return set(found)
    whole = frozenset(range(len(reps)))
    cadd = _centring_sum_table(centrings)
    action = _rotation_action(reps, centrings)
    candidates = _centring_subgroups(centrings, cadd)
    out: set = set()
    for h in set(found) | {whole}:
        gens = _generating_set(h, table)
        for d in candidates:
            if any(action[i][b] not in d for i in h for b in d):
                continue                   # would not close into a group
            if len(d) == c:
                # The whole centring kept: one answer, and it is the
                # translationengleiche subgroup this reduced set has
                # always stood for.
                if h != whole:
                    out.add(frozenset(i * c + a
                                      for i in h for a in range(c)))
                continue
            out |= _lifts(h, d, gens, c, ftable)
    out.discard(frozenset(range(len(reps) * c)))
    return out


def _to_symops(ops) -> tuple[SymOp, ...]:
    out = []
    for rot, tran in ops:
        r = np.array(rot, dtype=float).reshape(3, 3)
        t = np.array(tran, dtype=float) / DEN
        r.flags.writeable = False
        t.flags.writeable = False
        out.append(SymOp(r, t, _triplet(r, t)))
    return tuple(out)


def _triplet(rot, tran) -> str:
    """The operation written the way a CIF symmetry loop writes it.

    Handed to gemmi rather than formatted here: it already knows that
    a translation of 12/24 is written ``+1/2``, and a hand-rolled
    version of that is a page of fraction arithmetic that only has to
    be subtly wrong once.
    """
    import gemmi
    op = gemmi.Op("x,y,z")
    op.rot = [[int(round(v)) * gemmi.Op.DEN for v in row]
              for row in np.asarray(rot).reshape(3, 3)]
    op.tran = [int(round(v * gemmi.Op.DEN)) for v in np.asarray(tran)]
    return op.triplet()


# ======================================================================
#  NAMING
# ======================================================================

def _probe_lattice(group: SpaceGroup) -> Lattice:
    """A cell of the parent's shape and nothing more.

    Built by putting deliberately generic numbers through the group's
    own cell constraint, so a tetragonal parent gets a = b and a
    trigonal one gamma = 120, and no accidental right angle sneaks in
    to give the probe crystal symmetry the parent does not have.
    """
    return Lattice.from_parameters(
        *group.cell_constraint.apply(PROBE_PARAMETERS))


def _probe_crystal(lattice: Lattice, ops):
    """A crystal whose space group is exactly ``ops``: the orbits of two
    generic points, of two different species."""
    positions, species = [], []
    for number, seed in enumerate(PROBE_POINTS, start=1):
        point = np.array(seed)
        orbit: list = []
        for rot, tran in ops:
            r = np.array(rot, dtype=float).reshape(3, 3)
            image = np.mod(r @ point + np.array(tran) / DEN, 1.0)
            delta = np.array(orbit) - image if orbit else None
            if orbit is not None and len(orbit):
                delta -= np.round(delta)
                if np.any(np.linalg.norm(delta @ lattice.matrix, axis=1)
                          < 1e-4):
                    continue
            orbit.append(image)
        positions.extend(orbit)
        species.extend([number] * len(orbit))
    return lattice.matrix, np.array(positions), species


def _name(lattice: Lattice, ops, symprec: float = NAMING_SYMPREC):
    """``(SpaceGroup, P, p)`` for an operation list in an arbitrary
    basis, or ``None`` if it cannot be named with confidence.

    ``P`` and ``p`` are spglib's: ``x_standard = P x + p``.
    """
    cell = _probe_crystal(lattice, ops)
    try:
        ds = spglib.get_symmetry_dataset(cell, symprec=symprec)
    except Exception:                              # spglib raises its own
        return None
    if ds is None:
        return None
    # The probe crystal must have exactly the symmetry it was built
    # from.  More operations means the generic points were not generic
    # enough for this group and the name would be a lie.
    if len(ds.rotations) != len(ops):
        return None
    try:
        hall = spglib.get_spacegroup_type(ds.hall_number).hall_symbol
        group = SpaceGroup.from_hall(hall)
    except (ValueError, RuntimeError):             # pragma: no cover
        return None
    return (group, np.asarray(ds.transformation_matrix, dtype=float),
            np.asarray(ds.origin_shift, dtype=float))


# ======================================================================
#  THE ENUMERATION
# ======================================================================

def subgroups_of(group) -> list[Subgroup]:
    """Every subgroup of ``group`` in the same cell, one per conjugacy
    class: translationengleiche, klassengleiche, and both at once.

    Not only the maximal ones.  A descent of index 2 is the smallest
    step that can be taken, but it is rarely the one wanted: an
    ordering model usually knows the group it is heading for, and
    making it reachable only by descending through three dialogs is
    making the user do the subgroup lattice by hand.  Each entry says
    whether it is maximal, so the step-by-step path is still visible in
    the list.
    """
    return list(_subgroups_cached(SpaceGroup.from_any(group)))


def maximal_subgroups(group) -> list[Subgroup]:
    """Only the maximal subgroups: the one-step descents."""
    return [s for s in subgroups_of(group) if s.maximal]


@lru_cache(maxsize=64)
def _subgroups_cached(group: SpaceGroup) -> tuple[Subgroup, ...]:
    ops = _int_ops(group)
    reps, centrings = _reduced_ops(ops)
    c = len(centrings)
    if len(reps) < 2 and c < 2:         # P1 and friends: nothing below
        same_cell = []
    else:
        same_cell = _same_cell(group, ops, reps, centrings)
    out = _without_repeats(
        same_cell + _on_a_sublattice(group, ops, reps, centrings,
                                     _probe_lattice(group)))
    out.sort(key=lambda s: (s.index, s.group.number if s.group else 999,
                            s.symbol, s.k_index))
    return tuple(out)


def _without_repeats(candidates) -> list:
    """One row per descent, whichever pass found it.

    The two passes are not disjoint.  A sublattice of the parent's
    translations can have the same volume as the parent's own cell --
    for an I-centred group the integer lattice *is* one of them -- and
    the subgroup it carries is then a subgroup the same-cell pass has
    already found and described better.  What identifies a descent is
    the group it lands in and the transformation that gets there, so
    that is the key; the same-cell pass comes first and wins.

    An unnamed candidate is never merged: it cannot be applied, and
    its identity is the operations rather than a name.
    """
    seen, out = set(), []
    for candidate in candidates:
        if not candidate.named:
            out.append(candidate)
            continue
        key = (candidate.symbol, candidate.index,
               tuple(np.round(candidate.basis, 6).ravel()),
               tuple(np.round(candidate.origin_shift, 6)))
        if key in seen:
            continue
        seen.add(key)
        out.append(candidate)
    return out


def _same_cell(group, ops, reps, centrings) -> list:
    """Every subgroup that needs no new cell, one per conjugacy class."""
    c = len(centrings)
    table = _multiplication_table(reps, centrings)
    lattice = _probe_lattice(group)
    ftable = _full_table(reps, table, centrings)
    parent_order = len(reps) * c

    found = _all_subgroups_full(_all_subgroups(reps, table), reps,
                                table, centrings, ftable)
    maximal = {h for h in found if not any(h < k for k in found)}

    out = []
    # One per conjugacy class, and named once per class rather than
    # once per subgroup: naming is the expensive half, and Fm-3m's 97
    # proper subgroups are 32 classes.
    for indices, n_conjugates in _conjugacy_classes(ftable, found):
        child = _ops_from_full(indices, reps, centrings)
        kept = sum(1 for x in indices if x // c == 0)
        out.append(_describe_candidate(
            lattice, child, None,
            index=parent_order // len(child), k_index=c // kept,
            maximal=indices in maximal, n_conjugates=n_conjugates))
    return out


def _reconciles(subgroup: Subgroup) -> bool:
    """Does the name agree with the transformation that came with it?

    The two are found together and can be checked against each other.
    A group's operation count is a property of its *conventional* cell,
    and the transformation says how much bigger that cell is than the
    parent's: rutile's Cmmm subgroup has eight operations in rutile's
    own cell and sixteen in the doubled C-centred one it is named in,
    and 8 x 2 is the only way those two numbers are allowed to meet.
    For a subgroup on a sublattice the operations are counted in that
    sublattice's cell rather than the parent's, which is what
    :attr:`Subgroup.cell_ratio` allows for.
    A candidate that fails this is returned unnamed rather than
    mislabelled.
    """
    if subgroup.group is None:
        return False
    expected = len(subgroup.ops) * subgroup.cell_ratio
    return abs(subgroup.group.order - expected) < 1e-6


def _tidy(values):
    """Round away the floating-point dust in a transformation.

    Every entry of a basis change between two settings of the same
    lattice is a small rational; the ones spglib returns come back as
    0.9999999999999998 often enough to matter when they are then used
    as an exact test for "did anything move?".
    """
    arr = np.asarray(values, dtype=float)
    snapped = np.round(arr * 12.0) / 12.0
    return np.where(np.abs(arr - snapped) < 1e-8, snapped, arr)


# ======================================================================
#  WHAT A DESCENT COSTS
# ======================================================================

@dataclass(frozen=True)
class Split:
    """What one descent does to the sites of one structure.

    ``before`` and ``after`` are numbers of independent sites, and
    ``per_site`` says which of them split and into how many.  This is
    the number the whole feature exists for: a descent that splits
    nothing changes what each site is *allowed* to do without changing
    how many there are, and a list that does not say so looks broken.
    """

    before: int
    after: int
    per_site: tuple            # (label, element, multiplicity, pieces)
    ok: bool = True
    message: str = ""

    @property
    def splits(self) -> bool:
        return self.after > self.before

    def summary(self) -> str:
        if not self.ok:
            return self.message or "cannot be applied"
        if not self.splits:
            return f"{self.before} sites, none split"
        broken = [f"{label} into {pieces}"
                  for label, _el, _mult, pieces in self.per_site
                  if pieces > 1]
        return (f"{self.before} -> {self.after} sites: "
                + ", ".join(broken))


def describe_split(structure, subgroup: Subgroup) -> Split:
    """Apply the descent to a copy and report what happened to the
    sites.  Nothing is committed; this is what the dialog shows before
    the user chooses."""
    try:
        child, report = descend(structure, subgroup)
    except (ValueError, RuntimeError) as exc:
        return Split(structure.n_sites, structure.n_sites, (),
                     ok=False, message=str(exc))
    if not report.ok:
        return Split(structure.n_sites, structure.n_sites, (),
                     ok=False, message=report.message)

    from xtal.core import p1
    parent_cell = p1.expand(structure)
    child_cell = p1.expand(child)
    per_site = []
    for i, site in enumerate(structure.sites):
        # Which of the child's sites came out of this parent site: the
        # ones whose position is an image of it under the parent group.
        pieces = _pieces_of(parent_cell, child_cell, child, i,
                            subgroup)
        per_site.append((site.label or site.element, site.element,
                         parent_cell.multiplicity(i), pieces))
    return Split(structure.n_sites, child.n_sites, tuple(per_site))


def _pieces_of(parent_cell, child_cell, child, site_index, subgroup):
    """How many independent sites of the child come from one site of the
    parent.  Matched through the P1 cell, which both share."""
    orbit = parent_cell.frac[parent_cell.indices_of_site(site_index)]
    if not len(orbit):
        return 0
    moved = _map_forward(orbit, subgroup)
    lattice = child.lattice
    hits = set()
    for point in moved:
        d = child_cell.frac - point
        d -= np.round(d)
        dist = np.linalg.norm(d @ lattice.matrix, axis=1)
        k = int(np.argmin(dist))
        if dist[k] < 1e-2:
            hits.add(int(child_cell.site_idx[k]))
    return len(hits)


def _map_forward(frac, subgroup: Subgroup):
    """Parent fractional coordinates in the subgroup's setting.

    Every image of them, not one apiece.  Where the child's cell is
    larger than the parent's, one atom of the parent is several atoms
    of the child, and mapping only the parent cell's own copy finds one
    of them and reports that the site did not split -- which is wrong
    for every descent that enlarges the cell, the rhombohedral ones on
    hexagonal axes included.
    """
    if subgroup.keeps_the_cell:
        return np.mod(np.asarray(frac, dtype=float), 1.0)
    inverse = np.linalg.inv(subgroup.basis)
    moved = ((np.asarray(frac, dtype=float) - subgroup.origin_shift)
             @ inverse)
    cosets = _lattice_cosets(inverse, subgroup.volume_ratio)
    return np.mod((moved[:, None, :] + cosets[None]).reshape(-1, 3),
                  1.0)


def _lattice_cosets(inverse, volume_ratio: float) -> np.ndarray:
    """The parent's lattice translations, inside the child's cell.

    There are exactly ``volume_ratio`` of them, which is what stops the
    search rather than a guess about how far to look.
    """
    wanted = int(round(volume_ratio))
    if wanted <= 1:
        return np.zeros((1, 3))
    keep: list = []
    reach = 1
    while len(keep) < wanted:
        keep = []
        for i in range(-reach, reach + 1):
            for j in range(-reach, reach + 1):
                for k in range(-reach, reach + 1):
                    point = np.mod(np.array([i, j, k], dtype=float)
                                   @ inverse, 1.0)
                    gap = np.abs(np.asarray(keep) - point) if keep else None
                    if keep and np.any(np.all(
                            np.minimum(gap, 1.0 - gap) < 1e-6, axis=1)):
                        continue
                    keep.append(point)
        reach += 1
        if reach > 6:                    # cannot happen for a lattice
            break
    return np.array(keep[:wanted])


# ======================================================================
#  DESCENDING
# ======================================================================

def descend(structure, subgroup: Subgroup, tol: float | None = None):
    """Drop a structure into one of its maximal subgroups.

    Not a relabel.  Putting the smaller group on the existing sites
    loses atoms -- quartz's oxygen has multiplicity 6 in P3_221 and 3
    in P3_2, so the two sites written down would expand to six atoms
    where there were nine.  The operation is: expand to P1 under the
    parent, re-express in the subgroup's setting if it needs one, then
    find an asymmetric unit inside those atoms under the child, which
    is exactly what ``set_space_group(..., mode="impose")`` does.
    """
    from xtal.core import symmetry

    if subgroup.group is None:
        raise ValueError(
            "this subgroup has no name in a standard setting, so it "
            "cannot be adopted")
    tol = symmetry.MATCH_TOL if tol is None else float(tol)

    work = structure
    if not subgroup.keeps_the_cell:
        from xtal.core import supercell
        work = supercell.change_setting(structure, subgroup.basis,
                                        subgroup.origin_shift)
    return symmetry.set_space_group(work, subgroup.group, "impose", tol)


def basis_description(subgroup: Subgroup) -> str:
    """The basis change in the form a crystallographer writes it:
    ``a' = a-b, b' = a+b, c' = c``.

    Conjugate subgroups -- the three tetragonal descents of a cubic
    group, the four rhombohedral ones -- are the same group name at the
    same index and differ only here, so without this the list has rows
    nobody can tell apart.
    """
    if subgroup.keeps_the_cell:
        return "same axes, same origin"
    names = "abc"
    if np.allclose(subgroup.basis, np.eye(3), atol=1e-9):
        return ("same axes; origin at "
                + ", ".join(_short(v) for v in subgroup.origin_shift))
    parts = []
    for row in range(3):
        terms = ""
        for col in range(3):
            value = subgroup.basis[row][col]
            if abs(value) < 1e-9:
                continue
            sign = "-" if value < 0 else ("+" if terms else "")
            magnitude = "" if abs(abs(value) - 1) < 1e-9 else \
                _short(abs(value))
            terms += f"{sign}{magnitude}{names[col]}"
        parts.append(f"{names[row]}' = {terms or '0'}")
    text = ", ".join(parts)
    if not np.allclose(subgroup.origin_shift, 0.0, atol=1e-9):
        text += ("; origin at "
                 + ", ".join(_short(v) for v in subgroup.origin_shift))
    return text


def _short(value: float) -> str:
    from fractions import Fraction
    f = Fraction(float(value)).limit_denominator(12)
    if abs(float(f) - value) > 1e-6:
        return f"{value:.3f}"
    return str(f.numerator) if f.denominator == 1 else str(f)
