"""
xtal.core.subgroups
===================
Descending to a maximal subgroup: computing the subgroups, and -- the
part that actually costs something -- naming them.

Raising the symmetry of a structure is a *measurement*: spglib looks at
the coordinates and reports what it finds, and there is one answer.
Lowering it is a **choice**.  A group has several maximal subgroups,
each of which splits a different orbit into independent pieces, and
picking one is the first step of every distortion model, every ordering
model and every displacive phase transition.  So this module's job is
to lay out the choices, say what each one costs, and hand back
something the rest of the application can apply.

**Translationengleiche subgroups only** (k-index 1): the same lattice
of translations, a subset of the operations.  No cell is doubled and no
superstructure appears, so nothing here needs the Bilbao tables.

Two halves, and the second is the hard one:

**Finding them** is a subgroup-lattice walk over the operations reduced
modulo the lattice centring.  The reduction is not an optimisation, it
is what makes the problem finite in practice -- Fm-3m has 192
operations and 48 once the centring is divided out, and the difference
between closing subsets of 48 and of 192 is the difference between
instant and hopeless.  The walk starts from the cyclic subgroups and
repeatedly adjoins one more operation, which finds every subgroup
regardless of how many generators it needs; the familiar "every
crystallographic point group is generated by at most three elements"
shortcut is neither used nor relied on.

**Naming them** is the work this module exists for.  The operations
come out in the *parent's* basis, and most subgroups are not in their
standard setting there: asking gemmi to recognise the raw operation
list names about 11 of the 27 maximal subgroups of the four structures
in the test suite and returns nothing for the rest -- and among the
nameless ones sits, for rutile, the only descent that splits anything.
A subgroup that can only be offered as a list of operations is not
something anyone can choose from.

The way out is to build a crystal that *has* the subgroup as its
symmetry and ask spglib to identify it, because spglib answers with the
transformation to the standard setting as well as the name.  Two
generic points, of two different species, are given the orbit of the
candidate operation set in a cell of the parent's shape.  A generic
point has trivial site symmetry, so the orbit's symmetry is exactly the
group that generated it -- with one caveat that the second species is
there to cover: a *single* orbit can acquire an accidental inversion
centre about its own centroid, which is how a naive version of this
names P4_2nm as P4_2/mnm.  Two unrelated points cannot both acquire the
same accidental operation.

Every answer is checked: spglib has to report exactly as many
operations as were asked about, or the candidate is returned unnamed
rather than mislabelled.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from functools import lru_cache

import numpy as np
import spglib

from xtal.core.lattice import Lattice
from xtal.core.spacegroup import SpaceGroup, SymOp

# Operations are held as integers here, not floats: a subgroup is
# decided by exact equality of translations like 1/3 and 1/4, and
# 1/3 is not a float.  gemmi's denominator of 24 covers every
# translation a space group has.
DEN = 24
IDENTITY_ROT = (1, 0, 0, 0, 1, 0, 0, 0, 1)

# Two points with no site symmetry, unrelated to each other and to any
# special position.  Their orbits are the crystal whose symmetry spglib
# is asked to name.
PROBE_POINTS = (
    (0.1234567, 0.2345678, 0.3456789),
    (0.4271839, 0.0937261, 0.1783952),
)

# The shape of the cell the probe crystal is built in.  Only the
# *metric symmetry* matters, so these are deliberately generic numbers
# put through the parent group's own cell constraint: a group whose
# subgroups are being named must not be handed a cell with more metric
# symmetry than it has, or the naming inherits symmetry the structure
# never had.
PROBE_PARAMETERS = (5.1, 6.3, 7.7, 83.0, 97.0, 113.0)

NAMING_SYMPREC = 1e-5


# ======================================================================
#  A SUBGROUP
# ======================================================================

@dataclass(frozen=True)
class Subgroup:
    """One maximal translationengleiche subgroup of a space group.

    ``ops`` is in the **parent's** basis, which is where it was found.
    ``group`` is the same set of operations named in its own standard
    setting, and ``basis``/``origin_shift`` are how to get there:

        new lattice rows = basis @ old lattice rows
        x_new            = (x_old - origin_shift_old) @ inv(basis)

    For a good half of all subgroups the basis is the identity and the
    shift is zero, which is the case the descent costs nothing at all:
    not one atom moves and the cell is untouched.
    """

    index: int
    ops: tuple[SymOp, ...]
    group: SpaceGroup | None
    basis: np.ndarray                  # (3,3), rows = new vectors
    origin_shift: np.ndarray           # (3,) in the parent's basis
    maximal: bool = True
    n_conjugates: int = 1
    _cache: dict = field(default_factory=dict, repr=False,
                         compare=False)

    @property
    def named(self) -> bool:
        return self.group is not None

    @property
    def symbol(self) -> str:
        return self.group.short_name if self.group else "unnamed"

    @property
    def order(self) -> int:
        return len(self.ops)

    @property
    def keeps_the_cell(self) -> bool:
        """True when adopting this subgroup moves nothing: same basis,
        same origin, same coordinates, only fewer operations."""
        return (np.allclose(self.basis, np.eye(3), atol=1e-9)
                and np.allclose(self.origin_shift, 0.0, atol=1e-9))

    @property
    def volume_ratio(self) -> float:
        """Volume of the subgroup's conventional cell, over the
        parent's.  A translationengleiche subgroup keeps the lattice,
        but its *conventional* cell can be a different multiple of the
        primitive one -- the rhombohedral subgroups of a cubic group
        are the usual case, at three times the volume."""
        return abs(float(np.linalg.det(self.basis)))

    def describe(self) -> str:
        where = ("same cell and origin" if self.keeps_the_cell
                 else "new setting")
        return (f"{self.symbol} (#{self.group.number}), index "
                f"{self.index}, {where}" if self.group else
                f"unnamed, index {self.index}")

    def __repr__(self) -> str:
        return f"Subgroup({self.symbol}, index {self.index})"


# ======================================================================
#  INTEGER OPERATIONS
# ======================================================================
#
#  An operation is (rot, tran): nine ints and three ints over DEN.
#  Composition and comparison are exact, which is the whole point.

def _int_ops(group: SpaceGroup):
    out = []
    for op in group.operations:
        rot = tuple(int(round(v)) for v in np.asarray(op.rot).reshape(9))
        tran = tuple(int(round(v * DEN)) % DEN for v in op.trans)
        out.append((rot, tran))
    return out


def _compose(a, b):
    ra, ta = a
    rb, tb = b
    rot = tuple(sum(ra[3 * i + k] * rb[3 * k + j] for k in range(3))
                for i in range(3) for j in range(3))
    tran = tuple((sum(ra[3 * i + k] * tb[k] for k in range(3)) + ta[i])
                 % DEN for i in range(3))
    return rot, tran


def _centrings(ops) -> list:
    """The pure lattice translations in the operation list."""
    return [tran for rot, tran in ops if rot == IDENTITY_ROT]


def _canonical(op, centrings):
    """The operation's representative modulo the centring translations.

    Two operations that differ by a centring translation are the same
    operation of the group *modulo the lattice*, and a
    translationengleiche subgroup either contains both or neither.
    """
    rot, tran = op
    return rot, min(tuple((tran[i] + c[i]) % DEN for i in range(3))
                    for c in centrings)


def _reduced(group: SpaceGroup):
    """(representatives, centrings): the group modulo its centring, with
    the identity first."""
    ops = _int_ops(group)
    centrings = _centrings(ops)
    identity = _canonical((IDENTITY_ROT, (0, 0, 0)), centrings)
    reps = sorted({_canonical(op, centrings) for op in ops})
    reps.remove(identity)
    return [identity] + reps, centrings


def _multiplication_table(reps, centrings):
    """``table[i][j]`` is the index of ``rep_i . rep_j``.

    Every closure below is then integer bookkeeping over indices, which
    is what turns Fm-3m's enumeration from half a minute into a tenth
    of a second.
    """
    where = {op: i for i, op in enumerate(reps)}
    return [[where[_canonical(_compose(reps[i], reps[j]), centrings)]
             for j in range(len(reps))] for i in range(len(reps))]


def _close(seed, table) -> frozenset:
    """The subgroup generated by ``seed`` (indices into the table)."""
    elements = set(seed)
    elements.add(0)
    frontier = list(elements)
    generators = sorted(elements)
    while frontier:
        fresh = []
        for x in frontier:
            row = table[x]
            for g in generators:
                y = row[g]
                if y not in elements:
                    elements.add(y)
                    fresh.append(y)
        frontier = fresh
    return frozenset(elements)


def _all_subgroups(reps, table) -> set:
    """Every proper subgroup, as a frozenset of indices.

    Walks the subgroup lattice upwards from the cyclic subgroups: start
    with what one element generates, then repeatedly adjoin one more
    operation to everything found so far.  Slower than trying every
    subset of three elements and correct without assuming a bound on
    the number of generators, which stops being true the moment this is
    extended past the translationengleiche case.

    The trivial subgroup is one of the answers: dropping every rotation
    and keeping only the lattice is a descent like any other, and it is
    the one the rest of the application calls Reduce to P1.
    """
    n = len(reps)
    found: set = {frozenset({0})}
    frontier: set = set()
    for g in range(1, n):
        h = _close([g], table)
        if len(h) < n and h not in found:
            found.add(h)
            frontier.add(h)
    while frontier:
        grown = set()
        for h in frontier:
            for g in range(1, n):
                if g in h:
                    continue
                k = _close(h | {g}, table)
                if len(k) < n and k not in found:
                    found.add(k)
                    grown.add(k)
        frontier = grown
    return found


def _inverses(table) -> list:
    """``inv[g]`` is the index of the inverse of operation ``g``."""
    return [next(m for m in range(len(table)) if row[m] == 0)
            for row in table]


def _conjugacy_classes(table, found) -> list:
    """Group the subgroups into conjugacy classes under the parent.

    **Conjugate subgroups are the same descent.**  Fm-3m's three
    tetragonal subgroups differ only in which cubic axis they keep, and
    the parent's own three-fold carries any one of them onto any other
    -- so a structure that has Fm-3m as its symmetry comes out of all
    three as the same crystal, in the same group and the same cell.

    Not with the same coordinates, and the difference is worth being
    exact about: the three results are related by an operation of the
    parent, so they sit at different origins and on different axes
    inside that cell.  They are congruent, not identical -- an
    equivalent setting of one structure rather than three structures.
    Which of the equivalent settings you get is the parent's choice of
    axes and not a decision anybody can make usefully, so offering it
    as a choice is worse than not offering it: the orientation only
    becomes real once a distortion has been applied, and then it is the
    distortion that carries it and not this list.

    Returns ``(representative, size)`` per class, with a deterministic
    representative so the list does not reshuffle between runs.
    """
    inv = _inverses(table)
    classes, seen = [], set()
    for h in sorted(found, key=lambda s: (len(s), sorted(s))):
        if h in seen:
            continue
        orbit = set()
        for g in range(len(table)):
            gi = inv[g]
            orbit.add(frozenset(table[table[g][k]][gi] for k in h))
        seen |= orbit
        classes.append((min(orbit, key=sorted), len(orbit)))
    return classes


def _expand(indices, reps, centrings) -> list:
    """A reduced subgroup back into full operations: every
    representative, times every centring translation."""
    out = []
    for i in sorted(indices):
        rot, tran = reps[i]
        for c in centrings:
            out.append((rot, tuple((tran[k] + c[k]) % DEN
                                   for k in range(3))))
    return out


def _to_symops(ops) -> tuple[SymOp, ...]:
    out = []
    for rot, tran in ops:
        r = np.array(rot, dtype=float).reshape(3, 3)
        t = np.array(tran, dtype=float) / DEN
        r.flags.writeable = False
        t.flags.writeable = False
        out.append(SymOp(r, t, _triplet(r, t)))
    return tuple(out)


def _triplet(rot, tran) -> str:
    """The operation written the way a CIF symmetry loop writes it.

    Handed to gemmi rather than formatted here: it already knows that
    a translation of 12/24 is written ``+1/2``, and a hand-rolled
    version of that is a page of fraction arithmetic that only has to
    be subtly wrong once.
    """
    import gemmi
    op = gemmi.Op("x,y,z")
    op.rot = [[int(round(v)) * gemmi.Op.DEN for v in row]
              for row in np.asarray(rot).reshape(3, 3)]
    op.tran = [int(round(v * gemmi.Op.DEN)) for v in np.asarray(tran)]
    return op.triplet()


# ======================================================================
#  NAMING
# ======================================================================

def _probe_lattice(group: SpaceGroup) -> Lattice:
    """A cell of the parent's shape and nothing more.

    Built by putting deliberately generic numbers through the group's
    own cell constraint, so a tetragonal parent gets a = b and a
    trigonal one gamma = 120, and no accidental right angle sneaks in
    to give the probe crystal symmetry the parent does not have.
    """
    return Lattice.from_parameters(
        *group.cell_constraint.apply(PROBE_PARAMETERS))


def _probe_crystal(lattice: Lattice, ops):
    """A crystal whose space group is exactly ``ops``: the orbits of two
    generic points, of two different species."""
    positions, species = [], []
    for number, seed in enumerate(PROBE_POINTS, start=1):
        point = np.array(seed)
        orbit: list = []
        for rot, tran in ops:
            r = np.array(rot, dtype=float).reshape(3, 3)
            image = np.mod(r @ point + np.array(tran) / DEN, 1.0)
            delta = np.array(orbit) - image if orbit else None
            if orbit is not None and len(orbit):
                delta -= np.round(delta)
                if np.any(np.linalg.norm(delta @ lattice.matrix, axis=1)
                          < 1e-4):
                    continue
            orbit.append(image)
        positions.extend(orbit)
        species.extend([number] * len(orbit))
    return lattice.matrix, np.array(positions), species


def _name(lattice: Lattice, ops, symprec: float = NAMING_SYMPREC):
    """``(SpaceGroup, P, p)`` for an operation list in an arbitrary
    basis, or ``None`` if it cannot be named with confidence.

    ``P`` and ``p`` are spglib's: ``x_standard = P x + p``.
    """
    cell = _probe_crystal(lattice, ops)
    try:
        ds = spglib.get_symmetry_dataset(cell, symprec=symprec)
    except Exception:                              # spglib raises its own
        return None
    if ds is None:
        return None
    # The probe crystal must have exactly the symmetry it was built
    # from.  More operations means the generic points were not generic
    # enough for this group and the name would be a lie.
    if len(ds.rotations) != len(ops):
        return None
    try:
        hall = spglib.get_spacegroup_type(ds.hall_number).hall_symbol
        group = SpaceGroup.from_hall(hall)
    except (ValueError, RuntimeError):             # pragma: no cover
        return None
    return (group, np.asarray(ds.transformation_matrix, dtype=float),
            np.asarray(ds.origin_shift, dtype=float))


# ======================================================================
#  THE ENUMERATION
# ======================================================================

def subgroups_of(group) -> list[Subgroup]:
    """Every translationengleiche subgroup of ``group``, one per
    conjugacy class.

    Not only the maximal ones.  A descent of index 2 is the smallest
    step that can be taken, but it is rarely the one wanted: an
    ordering model usually knows the group it is heading for, and
    making it reachable only by descending through three dialogs is
    making the user do the subgroup lattice by hand.  Each entry says
    whether it is maximal, so the step-by-step path is still visible in
    the list.
    """
    return list(_subgroups_cached(SpaceGroup.from_any(group)))


def maximal_subgroups(group) -> list[Subgroup]:
    """Only the maximal subgroups: the one-step descents."""
    return [s for s in subgroups_of(group) if s.maximal]


@lru_cache(maxsize=64)
def _subgroups_cached(group: SpaceGroup) -> tuple[Subgroup, ...]:
    reps, centrings = _reduced(group)
    if len(reps) < 2:                   # P1 and friends: nothing below
        return ()
    table = _multiplication_table(reps, centrings)
    lattice = _probe_lattice(group)

    found = _all_subgroups(reps, table)
    maximal = {h for h in found if not any(h < k for k in found)}

    out = []
    # One per conjugacy class, and named once per class rather than
    # once per subgroup: naming is the expensive half, and Fm-3m's 97
    # proper subgroups are 32 classes.
    for indices, n_conjugates in _conjugacy_classes(table, found):
        ops = _expand(indices, reps, centrings)
        named = _name(lattice, ops)
        if named is None:
            child, basis, shift = None, np.eye(3), np.zeros(3)
        else:
            child, p_matrix, p_shift = named
            # spglib gives x_std = P x + p; the application works in
            # lattice rows and a shift of the origin, so invert it.
            basis = np.linalg.inv(p_matrix).T
            shift = -np.linalg.solve(p_matrix, p_shift)
            basis = _tidy(basis)
            # The origin shift is only defined modulo a lattice
            # translation, and "origin at 0, 0, 1/2" is the form it is
            # written in.
            shift = np.mod(_tidy(shift), 1.0)
            shift = _tidy(np.where(np.abs(shift - 1.0) < 1e-9, 0.0,
                                   shift))
        candidate = Subgroup(
            index=len(reps) // len(indices),
            ops=_to_symops(ops), group=child,
            basis=np.asarray(basis, dtype=float),
            origin_shift=np.asarray(shift, dtype=float),
            maximal=indices in maximal, n_conjugates=n_conjugates)
        out.append(candidate if _reconciles(candidate) else
                   Subgroup(index=candidate.index, ops=candidate.ops,
                            group=None, basis=np.eye(3),
                            origin_shift=np.zeros(3),
                            maximal=candidate.maximal,
                            n_conjugates=n_conjugates))

    out.sort(key=lambda s: (s.index, s.group.number if s.group else 999,
                            s.symbol))
    return tuple(out)


def _reconciles(subgroup: Subgroup) -> bool:
    """Does the name agree with the transformation that came with it?

    The two are found together and can be checked against each other.
    A group's operation count is a property of its *conventional* cell,
    and the transformation says how much bigger that cell is than the
    parent's: rutile's Cmmm subgroup has eight operations in rutile's
    own cell and sixteen in the doubled C-centred one it is named in,
    and 8 x 2 is the only way those two numbers are allowed to meet.
    A candidate that fails this is returned unnamed rather than
    mislabelled.
    """
    if subgroup.group is None:
        return False
    expected = len(subgroup.ops) * subgroup.volume_ratio
    return abs(subgroup.group.order - expected) < 1e-6


def _tidy(values):
    """Round away the floating-point dust in a transformation.

    Every entry of a basis change between two settings of the same
    lattice is a small rational; the ones spglib returns come back as
    0.9999999999999998 often enough to matter when they are then used
    as an exact test for "did anything move?".
    """
    arr = np.asarray(values, dtype=float)
    snapped = np.round(arr * 12.0) / 12.0
    return np.where(np.abs(arr - snapped) < 1e-8, snapped, arr)


# ======================================================================
#  WHAT A DESCENT COSTS
# ======================================================================

@dataclass(frozen=True)
class Split:
    """What one descent does to the sites of one structure.

    ``before`` and ``after`` are numbers of independent sites, and
    ``per_site`` says which of them split and into how many.  This is
    the number the whole feature exists for: a descent that splits
    nothing changes what each site is *allowed* to do without changing
    how many there are, and a list that does not say so looks broken.
    """

    before: int
    after: int
    per_site: tuple            # (label, element, multiplicity, pieces)
    ok: bool = True
    message: str = ""

    @property
    def splits(self) -> bool:
        return self.after > self.before

    def summary(self) -> str:
        if not self.ok:
            return self.message or "cannot be applied"
        if not self.splits:
            return f"{self.before} sites, none split"
        broken = [f"{label} into {pieces}"
                  for label, _el, _mult, pieces in self.per_site
                  if pieces > 1]
        return (f"{self.before} -> {self.after} sites: "
                + ", ".join(broken))


def describe_split(structure, subgroup: Subgroup) -> Split:
    """Apply the descent to a copy and report what happened to the
    sites.  Nothing is committed; this is what the dialog shows before
    the user chooses."""
    try:
        child, report = descend(structure, subgroup)
    except (ValueError, RuntimeError) as exc:
        return Split(structure.n_sites, structure.n_sites, (),
                     ok=False, message=str(exc))
    if not report.ok:
        return Split(structure.n_sites, structure.n_sites, (),
                     ok=False, message=report.message)

    from xtal.core import p1
    parent_cell = p1.expand(structure)
    child_cell = p1.expand(child)
    per_site = []
    for i, site in enumerate(structure.sites):
        # Which of the child's sites came out of this parent site: the
        # ones whose position is an image of it under the parent group.
        pieces = _pieces_of(parent_cell, child_cell, child, i,
                            subgroup)
        per_site.append((site.label or site.element, site.element,
                         parent_cell.multiplicity(i), pieces))
    return Split(structure.n_sites, child.n_sites, tuple(per_site))


def _pieces_of(parent_cell, child_cell, child, site_index, subgroup):
    """How many independent sites of the child come from one site of the
    parent.  Matched through the P1 cell, which both share."""
    orbit = parent_cell.frac[parent_cell.indices_of_site(site_index)]
    if not len(orbit):
        return 0
    moved = _map_forward(orbit, subgroup)
    lattice = child.lattice
    hits = set()
    for point in moved:
        d = child_cell.frac - point
        d -= np.round(d)
        dist = np.linalg.norm(d @ lattice.matrix, axis=1)
        k = int(np.argmin(dist))
        if dist[k] < 1e-2:
            hits.add(int(child_cell.site_idx[k]))
    return len(hits)


def _map_forward(frac, subgroup: Subgroup):
    """Parent fractional coordinates in the subgroup's setting."""
    if subgroup.keeps_the_cell:
        return np.mod(np.asarray(frac, dtype=float), 1.0)
    moved = (np.asarray(frac, dtype=float) - subgroup.origin_shift)
    return np.mod(moved @ np.linalg.inv(subgroup.basis), 1.0)


# ======================================================================
#  DESCENDING
# ======================================================================

def descend(structure, subgroup: Subgroup, tol: float | None = None):
    """Drop a structure into one of its maximal subgroups.

    Not a relabel.  Putting the smaller group on the existing sites
    loses atoms -- quartz's oxygen has multiplicity 6 in P3_221 and 3
    in P3_2, so the two sites written down would expand to six atoms
    where there were nine.  The operation is: expand to P1 under the
    parent, re-express in the subgroup's setting if it needs one, then
    find an asymmetric unit inside those atoms under the child, which
    is exactly what ``set_space_group(..., mode="impose")`` does.
    """
    from xtal.core import symmetry

    if subgroup.group is None:
        raise ValueError(
            "this subgroup has no name in a standard setting, so it "
            "cannot be adopted")
    tol = symmetry.MATCH_TOL if tol is None else float(tol)

    work = structure
    if not subgroup.keeps_the_cell:
        from xtal.core import supercell
        work = supercell.change_setting(structure, subgroup.basis,
                                        subgroup.origin_shift)
    return symmetry.set_space_group(work, subgroup.group, "impose", tol)


def basis_description(subgroup: Subgroup) -> str:
    """The basis change in the form a crystallographer writes it:
    ``a' = a-b, b' = a+b, c' = c``.

    Conjugate subgroups -- the three tetragonal descents of a cubic
    group, the four rhombohedral ones -- are the same group name at the
    same index and differ only here, so without this the list has rows
    nobody can tell apart.
    """
    if subgroup.keeps_the_cell:
        return "same axes, same origin"
    names = "abc"
    if np.allclose(subgroup.basis, np.eye(3), atol=1e-9):
        return ("same axes; origin at "
                + ", ".join(_short(v) for v in subgroup.origin_shift))
    parts = []
    for row in range(3):
        terms = ""
        for col in range(3):
            value = subgroup.basis[row][col]
            if abs(value) < 1e-9:
                continue
            sign = "-" if value < 0 else ("+" if terms else "")
            magnitude = "" if abs(abs(value) - 1) < 1e-9 else \
                _short(abs(value))
            terms += f"{sign}{magnitude}{names[col]}"
        parts.append(f"{names[row]}' = {terms or '0'}")
    text = ", ".join(parts)
    if not np.allclose(subgroup.origin_shift, 0.0, atol=1e-9):
        text += ("; origin at "
                 + ", ".join(_short(v) for v in subgroup.origin_shift))
    return text


def _short(value: float) -> str:
    from fractions import Fraction
    f = Fraction(float(value)).limit_denominator(12)
    if abs(float(f) - value) > 1e-6:
        return f"{value:.3f}"
    return str(f.numerator) if f.denominator == 1 else str(f)
